# griznog
# See: https://docs.gunicorn.org/en/latest/deploy.html

# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /srv/nginx_error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /srv/nginx_access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 4096;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen 80;
        server_name umbrella-dev.czbiohub.org;  # or http://10.50.120.75:8000
	root /srv/czii-umbrella-django/frontend;
	#index index.html;
	autoindex off;
        location /next {
                proxy_pass http://localhost:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }
  	#location /next/tomograms {
        #    alias /srv/czii-umbrella-django/frontend/out;
        #    index tomograms.html;
	#    try_files $uri $uri/ /tomograms.html =404;

	    #rewrite ^/next/tomograms/cryo_grids$ /next/cryo_grids permanent;
	    #rewrite ^/next/tomograms/annotations$ /next/annotations permanent;
        #}
	#location /next/cryo_grids {
	#    alias /srv/czii-umbrella-django/frontend/out;
	#    index cryo_grids.html;
	#    try_files $uri $uri/ /ocryo_grids.html =404;
	#    #rewrite ^/next/cryo_grids/annotations$ /next/annotations permanent;
	#    #rewrite ^/next/cryo_grids/tomograms$ /next/tomograms permanent;
	#}

	#location /next/annotations {
        #    alias /srv/czii-umbrella-django/frontend/out;
	#    index annotations.html;
	#    try_files $uri $uri/ /annotations.html =404;

	    #rewrite ^/next/annotations/cryo_grids$ /next/cryo_grids permanent;
	    #rewrite ^/next/annotations/tomograms$ /next/tomograms permanent;
	#}

	#location /next/_next/static/ {
	#    alias /srv/czii-umbrella-django/frontend/out/_next/static/;
	#}
        location = /favicon.ico {
            access_log off;
            log_not_found off;
        }

        location / {
	    try_files $uri @proxy_to_app;
	}

	location @proxy_to_app {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            # we don't want nginx trying to do something clever with
            # redirects, we set the Host: header above already.
            proxy_redirect off;
            proxy_pass http://127.0.0.1:8000;  # Assuming gunicorn  is set to listen on 127.0.0.1:8000?
        }
    }
}
