# Generated by Django 5.0.2 on 2024-05-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_staticpath_alter_pathtype_static_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticpath",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("atlas", "grid atlas"),
                    ("parents", "parent image of the tomography images"),
                    ("sums", "sum image of the frames"),
                    ("frames", "frames"),
                    ("rawst", "raw tilt image stack"),
                    ("tangl", "tilt angles"),
                    ("mdoc", "mdoc"),
                    ("ctf", "ctf values"),
                    ("aln", "tilt alignments"),
                    ("rec", "all frame tomo recon"),
                    ("evn", "even frame tomo recon"),
                    ("odd", "odd frame tomo recon"),
                    ("deno", "denoised recon"),
                ],
                max_length=8,
                unique=True,
            ),
        ),
    ]
