# Generated by Django 5.0.2 on 2024-08-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0004_alter_staticpath_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticpath",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("atlas", "grid atlas"),
                    ("satlas", "grid atlas from screening"),
                    ("parents", "parent image of the tomography images"),
                    ("sums", "sum image of the frames"),
                    ("frames", "frames"),
                    ("rawst", "raw tilt image stack"),
                    ("tangl", "tilt angles"),
                    ("mdoc", "mdoc"),
                    ("ctf", "ctf values"),
                    ("aln", "tilt alignments"),
                    ("rec", "all frame tomo recon"),
                    ("evn", "even frame tomo recon"),
                    ("odd", "odd frame tomo recon"),
                    ("pick", "particle point annotation"),
                    ("seg", "segmentation"),
                    ("galr", "particle gallery"),
                ],
                max_length=8,
                unique=True,
            ),
        ),
    ]
