# Generated by Django 5.2.7 on 2025-12-17 02:15
"""
Data migration to fix incorrect base path in Path.overlay_path.

The init scripts incorrectly used /hpc/processing/group.czii instead of
/hpc/projects/group.czii. This migration fixes all affected Path records.
"""

from django.db import migrations
from django.db.models import Value
from django.db.models.functions import Replace


def fix_overlay_paths(apps, schema_editor):
    """Replace incorrect path prefix in all Path records."""
    Path = apps.get_model("stores", "Path")

    updated = Path.objects.filter(
        overlay_path__startswith="/hpc/processing/group.czii"
    ).update(
        overlay_path=Replace(
            "overlay_path",
            Value("/hpc/processing/group.czii"),
            Value("/hpc/projects/group.czii"),
        )
    )

    if updated:
        print(f"\n  Fixed {updated} Path records with incorrect base path")


def reverse_overlay_paths(apps, schema_editor):
    """Reverse the path fix (for rollback)."""
    Path = apps.get_model("stores", "Path")

    Path.objects.filter(
        overlay_path__startswith="/hpc/projects/group.czii"
    ).update(
        overlay_path=Replace(
            "overlay_path",
            Value("/hpc/projects/group.czii"),
            Value("/hpc/processing/group.czii"),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0007_alter_staticpath_data_type"),
    ]

    operations = [
        migrations.RunPython(fix_overlay_paths, reverse_overlay_paths),
    ]
