# Generated by Django 5.2.7 on 2026-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0008_fix_path_overlay_paths"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "cluster_id",
                    models.CharField(
                        help_text="Short identifier used in code (e.g. 'czii', 'bruno')",
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable display name", max_length=64),
                ),
                (
                    "http_base_url",
                    models.CharField(
                        help_text="Base URL of Caddy server, e.g. https://czii-onsite.czbiohub.org/ (no scope subdir)",
                        max_length=255,
                    ),
                ),
                ("ssh_hostname", models.CharField(max_length=128)),
                ("ssh_port", models.PositiveIntegerField(default=22)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
