# Generated by Django 5.2.7 on 2026-04-23 18:01

from django.db import migrations, models

REVIEW_TEMPLATES = [
    {
        "data_type": "proc_dir",
        "static_path": "/{workflow}/{msi_session}/{run}/proc_dir",
        "overlay_path": "/hpc/projects/group.czii/{scope}.processing/{workflow}/{msi_session}/{run}/",
    },
    {
        "data_type": "zarr_url",
        "static_path": "/{workflow}/{msi_session}/{run}/{vol_suffix}/{position}_Vol.zarr",
        "overlay_path": "{http_base}{scope}.processing/{workflow}/{msi_session}/{run}/{vol_suffix}/{position}_Vol.zarr",
    },
    {
        "data_type": "thumb_url",
        "static_path": "/aretomo3/{msi_session}/{run}/{thumb_kind}/",
        "overlay_path": "{http_base}{scope}.processing/aretomo3/{msi_session}/{run}/{thumb_kind}/",
    },
]


def seed_review_pathtypes(apps, schema_editor):
    StaticPath = apps.get_model("stores", "StaticPath")
    PathType = apps.get_model("stores", "PathType")
    for t in REVIEW_TEMPLATES:
        sp, _ = StaticPath.objects.update_or_create(
            data_type=t["data_type"],
            defaults={"static_path": t["static_path"]},
        )
        PathType.objects.update_or_create(
            static_path=sp,
            defaults={"overlay_path": t["overlay_path"]},
        )


def unseed_review_pathtypes(apps, schema_editor):
    StaticPath = apps.get_model("stores", "StaticPath")
    StaticPath.objects.filter(data_type__in=[t["data_type"] for t in REVIEW_TEMPLATES]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0010_seed_clusters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticpath",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("atlas", "grid atlas"),
                    ("satlas", "grid atlas from screening"),
                    ("parents", "parent image of the tomography images"),
                    ("sums", "sum image of the frames"),
                    ("frames", "frames"),
                    ("rawst", "raw tilt image stack"),
                    ("tangl", "tilt angles"),
                    ("mdoc", "mdoc"),
                    ("ctf", "ctf values"),
                    ("aln", "tilt alignments"),
                    ("imod", "aln in imod compatible format for relion"),
                    ("rec", "all frame tomo recon"),
                    ("evn", "even frame tomo recon"),
                    ("odd", "odd frame tomo recon"),
                    ("deno", "denoised tomo recon"),
                    ("pick", "particle point annotation"),
                    ("seg", "segmentation"),
                    ("galr", "particle gallery"),
                    ("proc_dir", "processing directory on cluster filesystem"),
                    ("zarr_url", "zarr volume URL for tomogram viewer"),
                    ("thumb_url", "thumbnail/CTF-thumbnail URL base"),
                ],
                max_length=16,
                unique=True,
            ),
        ),
        migrations.RunPython(seed_review_pathtypes, unseed_review_pathtypes),
    ]
