# Generated by Django 5.2.16 on 2026-08-21 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_alter_datakind_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathtype',
            name='cluster',
            field=models.ForeignKey(blank=True, help_text='Blank is the cluster-agnostic default, and the fallback. A row naming a cluster overrides that default on that cluster only.', null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.cluster'),
        ),
    ]
