# Generated by Django 5.2.16 on 2026-08-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_pathtype_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Name shown in the file-pattern dropdowns on Path type and Session plan, e.g. 'Tomo5 EER fractions'.", max_length=64)),
                ('list_glob', models.CharField(default='*', help_text='Narrows the remote listing before the regex runs. Must describe the same files as the regex.', max_length=128)),
                ('regex', models.CharField(help_text="Anchored, named groups, matched against the basename alone -- the directory is the PathType's half.", max_length=512)),
                ('sample_filenames', models.JSONField(blank=True, default=list, help_text='Real basenames this pattern must match. Checked on save, so put real file names here.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('data_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_patterns', to='stores.datakind')),
            ],
        ),
        migrations.AddField(
            model_name='pathtype',
            name='file_pattern',
            field=models.ForeignKey(blank=True, help_text='Filename convention normally found in this directory. A plan whose files are named differently overrides it on its path binding.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='path_types', to='stores.filepattern'),
        ),
    ]
