# Generated by Django 5.0.2 on 2024-05-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0002_rename_session_cryogrid_freezing_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MolecularTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="unique molecule attached to specific biological macromolecules to investigate the properties of the sample. For example, DAPI",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="plungefreezingplan",
            name="tag",
        ),
        migrations.AddField(
            model_name="sample",
            name="description",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="sample",
            name="name",
            field=models.CharField(
                help_text="unique sample name that you may use to search your grid for later. For example, lysosome",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="plungefreezingplan",
            name="tags",
            field=models.ManyToManyField(to="cryo_grids.moleculartag"),
        ),
    ]
