# Generated by Django 5.0.6 on 2024-06-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryo_grids', '0006_cryogrid_intended_project'),
        ('cryo_grids', '0006_cryogrid_user'),
    ]

    operations = [
    ]
