# Generated by Django 5.0.6 on 2024-07-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryo_grids', '0007_merge_20240621_1400'),
        ('cryo_grids', '0007_merge_20240621_1430'),
    ]

    operations = [
    ]
