# Generated by Django 5.0.6 on 2024-08-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryo_grids', '0008_merge_20240709_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryogrid',
            name='name',
            field=models.CharField(default='grid1', max_length=32),
        ),
    ]
