# Generated by Django 5.0.6 on 2024-09-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0009_alter_cryogrid_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryogrid",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
