# Generated by Django 5.0.6 on 2024-09-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0010_cryogrid_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryogrid",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
    ]
