# Generated by Django 5.0.2 on 2024-10-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0012_cane_max_pucks_cryogridbox_max_grids_dewar_max_canes_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cryogrid",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cryogrid",
            name="copy_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="cryogrid",
            unique_together={("name", "freezing_session", "freezing_plan", "copy_number")},
        ),
    ]
