# Generated by Django 5.0.6 on 2025-01-16 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "cryo_grids",
            "0013_alter_cryogrid_unique_together_cryogrid_copy_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plungefreezingsession",
            name="number_of_grids",
        ),
    ]
