# Generated by Django 5.0.6 on 2025-01-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0014_remove_plungefreezingsession_number_of_grids"),
    ]

    operations = [
        migrations.CreateModel(
            name="GridPreparationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blot_time",
                    models.FloatField(default=6.0, help_text="Blot time in seconds"),
                ),
                ("blot_force", models.FloatField(default=None, help_text="Blot force")),
                (
                    "blot_distance",
                    models.FloatField(default=None, help_text="blot distance"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, max_length=150)),
                ("protocol", models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
