# Generated by Django 5.0.6 on 2025-01-16 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cryo_grids",
            "0015_gridpreparationlog_specimen_cryogrid_grid_prep_log_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cryogrid",
            name="grid_prep_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cryo_grids.gridpreparationlog",
            ),
        ),
        migrations.AddField(
            model_name="cryogrid",
            name="specimen",
            field=models.ForeignKey(
                blank=True,
                help_text="referring to specimen",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cryo_grids.specimen",
            ),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="name",
            field=models.CharField(
                help_text="Enter each specimen name on a new line.", max_length=150,
            ),
        ),
    ]
