# Generated by Django 5.0.6 on 2025-01-17 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0016_cryogrid_grid_prep_log_cryogrid_specimen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plungefreezingsession",
            name="notes_page",
        ),
    ]
