# Generated by Django 5.0.6 on 2025-01-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0017_remove_plungefreezingsession_notes_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="specimen",
            name="sample",
            field=models.ManyToManyField(to="cryo_grids.sample"),
        ),
    ]
