# Generated by Django 5.0.6 on 2025-01-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0018_specimen_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridpreparationlog",
            name="grids",
            field=models.ManyToManyField(
                help_text="Associated cryo grids",
                related_name="prep_logs",
                to="cryo_grids.cryogrid",
            ),
        ),
        migrations.AlterField(
            model_name="gridpreparationlog",
            name="blot_distance",
            field=models.FloatField(default=None, help_text="Blot distance"),
        ),
    ]
