# Generated by Django 5.0.6 on 2025-01-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0019_gridpreparationlog_grids_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plungefreezingplan",
            name="tags",
        ),
        migrations.AddField(
            model_name="sample",
            name="tag",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name="MolecularTag",
        ),
    ]
