# Generated by Django 5.0.6 on 2025-01-18 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0020_remove_plungefreezingplan_tags_sample_tag_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cryogrid",
            unique_together={("name", "freezing_session", "copy_number")},
        ),
        migrations.RemoveField(
            model_name="cryogrid",
            name="freezing_plan",
        ),
        migrations.DeleteModel(
            name="PlungeFreezingPlan",
        ),
    ]
