# Generated by Django 5.0.6 on 2025-02-04 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confluence", "0003_alter_space_name_page"),
        ("cryo_grids", "0021_alter_cryogrid_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specimen",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="specimen",
            name="name",
        ),
        migrations.AddField(
            model_name="specimen",
            name="notes_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Confluence link for sample prep",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="confluence.page",
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="ontology",
            field=models.CharField(
                blank=True,
                help_text='ontology name and values to help database deposition. For example: "GO:0005764" for lysosome',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="tag",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name="Sample",
        ),
        migrations.AddField(
            model_name="specimen",
            name="sample",
            field=models.CharField(
                default="default_sample_name",
                help_text="unique sample name that you may use to search your grid for later. For example, lysosome",
                max_length=150,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
