# Generated by Django 5.0.6 on 2025-02-04 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0021_alter_cryogrid_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specimen",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="specimen",
            name="name",
        ),
        # Notes: Original migration added FK to confluence.page, but that app has been removed
        # This field was later replaced by documentation_page FK to external_links.ExternalResource
        # Keeping this as a no-op since the field was subsequently migrated in later migrations
        migrations.AddField(
            model_name="specimen",
            name="ontology",
            field=models.CharField(
                blank=True,
                help_text='ontology name and values to help database deposition. For example: "GO:0005764" for lysosome',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="tag",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name="Sample",
        ),
        migrations.AddField(
            model_name="specimen",
            name="sample",
            field=models.CharField(
                default="default_sample_name",
                help_text="unique sample name that you may use to search your grid for later. For example, lysosome",
                max_length=150,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
