# Generated by Django 5.0.6 on 2025-02-05 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0022_remove_specimen_sample_remove_specimen_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specimen",
            old_name="tag",
            new_name="tags",
        ),
    ]
