# Generated by Django 5.0.6 on 2025-02-12 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confluence", "0003_alter_space_name_page"),
        ("cryo_grids", "0023_rename_tag_specimen_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="plungefreezingsession",
            name="notes_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Confluence link for freezing session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="confluence.page",
            ),
        ),
    ]
