# Generated by Django 5.0.6 on 2025-02-12 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0023_rename_tag_specimen_tags"),
    ]

    operations = [
        # Notes: Original migration added FK to confluence.page, but that app has been removed
        # This field was later replaced by documentation_page FK to external_links.ExternalResource
        # Keeping this as a no-op since the field was subsequently migrated in later migrations
    ]
