# Generated by Django 5.0.6 on 2025-02-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0024_plungefreezingsession_notes_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryogrid",
            name="grid_prep_log",
        ),
        migrations.AddField(
            model_name="cryogrid",
            name="blot_distance",
            field=models.FloatField(default=0.0, blank=True, null=True, help_text="Blot distance"),
        ),
        migrations.AddField(
            model_name="cryogrid",
            name="blot_force",
            field=models.FloatField(default=0.0, blank=True, null=True, help_text="Blot force"),
        ),
        migrations.AddField(
            model_name="cryogrid",
            name="blot_time",
            field=models.FloatField(default=6.0, help_text="Blot time in seconds"),
        ),
        migrations.AddField(
            model_name="cryogrid",
            name="resource_link",
            field=models.URLField(
                blank=True,
                help_text="Link to additional resources related to this cryo-grid",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="GridPreparationLog",
        ),
    ]
