# Generated by Django 5.0.6 on 2025-02-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cryo_grids",
            "0025_remove_cryogrid_grid_prep_log_cryogrid_blot_distance_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="unique sample name that you may use to search your grid for later. For example, lysosome",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "ontology",
                    models.CharField(
                        blank=True,
                        help_text='ontology name and values to help database deposition. For example: "GO:0005764" for lysosome',
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="specimen",
            old_name="protocol",
            new_name="notes",
        ),
        migrations.AlterUniqueTogether(
            name="cryogrid",
            unique_together={("name", "freezing_session", "specimen", "copy_number")},
        ),
        migrations.RemoveField(
            model_name="specimen",
            name="ontology",
        ),
        migrations.RemoveField(
            model_name="specimen",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="specimen",
            name="tags",
        ),
        migrations.AlterField(
            model_name="cryogrid",
            name="blot_time",
            field=models.FloatField(
                default=6.0, help_text="Blot time in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="specimen",
            name="samples",
            field=models.ManyToManyField(
                blank=True,
                help_text="Associated samples from the Sample",
                to="cryo_grids.sample",
            ),
        ),
    ]
