# Generated by Django 5.2 on 2025-10-16 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryo_grids', '0027_puck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cane',
            name='color',
            field=models.CharField(choices=[('CF1E01', 'Red'), ('B9BAB2', 'Silver'), ('FFC0CB', 'Pink'), ('996699', 'Purple'), ('E5C100', 'Gold')], default='CF1E01', max_length=40),
        ),
        migrations.AlterField(
            model_name='cryogrid',
            name='freezing_session',
            field=models.ForeignKey(blank=True, help_text='who and when the grid was frozen', null=True, on_delete=django.db.models.deletion.CASCADE, to='cryo_grids.plungefreezingsession'),
        ),
        migrations.AlterField(
            model_name='puck',
            name='color',
            field=models.CharField(choices=[('CF1E01', 'Red'), ('dc6d0e', 'Orange'), ('416633', 'Green'), ('0000CC', 'Ultramarine Blue'), ('817B93', 'Lavendar'), ('000000', 'Black'), ('B9BAB2', 'Silver'), ('FFC0CB', 'Pink'), ('996699', 'Purple'), ('5C6C90', 'Silver Blue'), ('E5C100', 'Gold')], default='CF1E01', max_length=40),
        ),
    ]
