# Generated by Django on 2025-11-23
# Consolidated migration: Migrates from confluence notes_page to unified external_links

import django.db.models.deletion
from django.db import migrations, models


def populate_documentation_pages(apps, schema_editor):
    """
    Migrate cryo_grids FKs from old notes_page to new documentation_page.
    This is idempotent - safe to run multiple times.
    """
    PlungeFreezingSession = apps.get_model('cryo_grids', 'PlungeFreezingSession')
    Specimen = apps.get_model('cryo_grids', 'Specimen')
    ExternalResource = apps.get_model('external_links', 'ExternalResource')

    # Check if old columns still exist using Django's introspection API (works with SQLite, MySQL, PostgreSQL)
    connection = schema_editor.connection

    # Check if tables exist first
    tables = connection.introspection.table_names()
    has_session_table = 'cryo_grids_plungefreezingsession' in tables
    has_specimen_table = 'cryo_grids_specimen' in tables

    # Check if old columns exist
    has_session_notes_col = False
    has_specimen_notes_col = False

    if has_session_table:
        with connection.cursor() as cursor:
            columns = {col.name for col in connection.introspection.get_table_description(cursor, 'cryo_grids_plungefreezingsession')}
            has_session_notes_col = 'notes_page_id' in columns

    if has_specimen_table:
        with connection.cursor() as cursor:
            columns = {col.name for col in connection.introspection.get_table_description(cursor, 'cryo_grids_specimen')}
            has_specimen_notes_col = 'notes_page_id' in columns

    if not has_session_notes_col and not has_specimen_notes_col:
        print("Old notes_page columns not found - skipping cryo_grids FK migration")
        print("(This is expected if columns were already dropped)")
        return

    # Migrate PlungeFreezingSession.notes_page -> documentation_page
    session_migrated = 0
    session_skipped = 0

    if has_session_notes_col:
        for session in PlungeFreezingSession.objects.all():
            # Skip if already migrated (idempotent check)
            if session.documentation_page_id is not None:
                session_skipped += 1
                continue

            # Try to migrate from notes_page
            if hasattr(session, 'notes_page_id') and session.notes_page_id:
                try:
                    with schema_editor.connection.cursor() as cursor:
                        cursor.execute(
                            "SELECT url FROM confluence_page WHERE id = %s",
                            [session.notes_page_id]
                        )
                        row = cursor.fetchone()
                        if row:
                            page_url = row[0]
                            external = ExternalResource.objects.filter(
                                resource_type='doc_page',
                                system_name='Confluence',
                                url=page_url
                            ).first()
                            if external:
                                session.documentation_page = external
                                session.save()
                                session_migrated += 1
                except Exception as e:
                    print(f"Warning: Could not migrate notes_page for session {session.id}: {e}")

    # Migrate Specimen.notes_page -> documentation_page
    specimen_migrated = 0
    specimen_skipped = 0

    if has_specimen_notes_col:
        for specimen in Specimen.objects.all():
            # Skip if already migrated (idempotent check)
            if specimen.documentation_page_id is not None:
                specimen_skipped += 1
                continue

            # Try to migrate from notes_page
            if hasattr(specimen, 'notes_page_id') and specimen.notes_page_id:
                try:
                    with schema_editor.connection.cursor() as cursor:
                        cursor.execute(
                            "SELECT url FROM confluence_page WHERE id = %s",
                            [specimen.notes_page_id]
                        )
                        row = cursor.fetchone()
                        if row:
                            page_url = row[0]
                            external = ExternalResource.objects.filter(
                                resource_type='doc_page',
                                system_name='Confluence',
                                url=page_url
                            ).first()
                            if external:
                                specimen.documentation_page = external
                                specimen.save()
                                specimen_migrated += 1
                except Exception as e:
                    print(f"Warning: Could not migrate notes_page for specimen {specimen.id}: {e}")

    print(f"Cryo grids: Migrated {session_migrated} freezing session docs (skipped {session_skipped}), {specimen_migrated} specimen docs (skipped {specimen_skipped})")


def reverse_migration(apps, schema_editor):
    """Reverse migration - clear documentation_page FKs."""
    PlungeFreezingSession = apps.get_model('cryo_grids', 'PlungeFreezingSession')
    Specimen = apps.get_model('cryo_grids', 'Specimen')

    session_cleared = PlungeFreezingSession.objects.filter(documentation_page__isnull=False).update(documentation_page=None)
    specimen_cleared = Specimen.objects.filter(documentation_page__isnull=False).update(documentation_page=None)

    print(f"Cleared documentation_page for {session_cleared} sessions and {specimen_cleared} specimens")


class Migration(migrations.Migration):

    dependencies = [
        ('cryo_grids', '0029_alter_cryogridbox_unique_together_and_more'),
        ('external_links', '0003_migrate_legacy_docs'),
    ]

    operations = [
        # Step 1: Add new unified documentation_page fields
        migrations.AddField(
            model_name='plungefreezingsession',
            name='documentation_page',
            field=models.ForeignKey(
                blank=True,
                help_text='Documentation page for freezing session (Confluence, Benchling, etc.)',
                limit_choices_to={'resource_type': 'doc_page'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='freezing_session_docs',
                to='external_links.externalresource',
            ),
        ),
        migrations.AddField(
            model_name='specimen',
            name='documentation_page',
            field=models.ForeignKey(
                blank=True,
                help_text='Documentation page for sample prep (Confluence, Benchling, etc.)',
                limit_choices_to={'resource_type': 'doc_page'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='specimen_docs',
                to='external_links.externalresource',
            ),
        ),

        # Step 2: Migrate data from old columns to new columns
        migrations.RunPython(populate_documentation_pages, reverse_migration),

        # Step 3 & 4: Drop old foreign key constraints and columns
        # Note: These are intentionally noops. The columns can be removed manually in production
        # after verifying the migration. SQLite doesn't support DROP FOREIGN KEY and this
        # migration is designed to be idempotent and work across database backends.
        # migrations.RunSQL(
        #     sql="ALTER TABLE `cryo_grids_plungefreezingsession` DROP FOREIGN KEY `cryo_grids_plungefre_notes_page_id_149e2c4f_fk_confluenc`;",
        #     reverse_sql=migrations.RunSQL.noop,
        # ),
        # migrations.RunSQL(
        #     sql="ALTER TABLE `cryo_grids_specimen` DROP FOREIGN KEY `cryo_grids_specimen_notes_page_id_f8e533c7_fk_confluence_page_id`;",
        #     reverse_sql=migrations.RunSQL.noop,
        # ),
        # migrations.RunSQL(
        #     sql="ALTER TABLE `cryo_grids_plungefreezingsession` DROP COLUMN `notes_page_id`;",
        #     reverse_sql=migrations.RunSQL.noop,
        # ),
        # migrations.RunSQL(
        #     sql="ALTER TABLE `cryo_grids_specimen` DROP COLUMN `notes_page_id`;",
        #     reverse_sql=migrations.RunSQL.noop,
        # ),
    ]
