# Generated by Django 5.2.7 on 2025-12-11 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0029_alter_cryogridbox_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plungefreezingsession",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
