# Generated by Django 5.2.7 on 2026-03-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0031_migrate_to_unified_documentation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cane",
            name="color",
            field=models.CharField(
                choices=[
                    ("CF1E01", "Red"),
                    ("B9BAB2", "Silver"),
                    ("FFC0CB", "Pink"),
                    ("996699", "Purple"),
                    ("E5C100", "Gold"),
                    ("dc6d0e", "Orange"),
                ],
                default="CF1E01",
                max_length=40,
            ),
        ),
    ]
