# Generated by Django 5.2.7 on 2026-06-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cryo_grids", "0035_seed_long_form_screening_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="cell_component_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="sample",
            name="cell_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="sample",
            name="cell_strain_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sample",
            name="cell_strain_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="sample",
            name="cell_type_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sample",
            name="development_stage_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="sample",
            name="development_stage_ontology_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sample",
            name="disease_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="sample",
            name="disease_ontology_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sample",
            name="organism_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="sample",
            name="organism_taxid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cell_line", "Cell Line"),
                    ("in_silico", "In Silico"),
                    ("in_vitro", "In Vitro"),
                    ("organelle", "Organelle"),
                    ("organism", "Organism"),
                    ("organoid", "Organoid"),
                    ("other", "Other"),
                    ("primary_cell_culture", "Primary Cell Culture"),
                    ("tissue", "Tissue"),
                    ("virus", "Virus"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="tissue_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sample",
            name="tissue_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="cryogrid",
            name="blot_time",
            field=models.FloatField(default=0.0, help_text="Blot time in seconds", null=True),
        ),
        migrations.AlterField(
            model_name="plungefreezingsession",
            name="device_temperature",
            field=models.FloatField(
                default=0.0,
                help_text="Temperature of the freezing chamber in degree Celsius",
            ),
        ),
    ]
