# Generated by Django 5.2.7 on 2026-06-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryo_grids', '0036_sample_cell_component_name_sample_cell_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='development_stage_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='development_stage_ontology_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sample',
            name='disease_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='sample',
            name='disease_ontology_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
