# Generated by Django 5.0.1 on 2024-02-20 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('confluence', '0001_initial'),
        ('googledoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BD01', 'BD01 Human Organelle Library'), ('TRD05', 'TRD05 Data Integration')], default='TRD05', max_length=6, unique=True)),
                ('confluence_space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='confluence.space')),
                ('google_drive_folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='googledoc.drivefolder')),
            ],
        ),
    ]
