# Generated by Django 5.0.2 on 2024-05-30 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_description_alter_project_name'),
    ]

    operations = [
        # Note: Original migration altered FKs to confluence.space and clouddocs.drivefolder
        # These apps have been removed and fields were later replaced by documentation_space
        # FK to external_links.ExternalResource. Keeping this as a no-op.
    ]
