# Generated by Django 5.0.2 on 2024-05-30 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0003_alter_space_name_page'),
        ('googledoc', '0003_alter_drivefolder_name'),
        ('projects', '0003_project_description_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='confluence_space',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='confluence.space'),
        ),
        migrations.AlterField(
            model_name='project',
            name='google_drive_folder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='googledoc.drivefolder'),
        ),
    ]
