# Generated by Django on 2025-11-23
# Consolidated migration: Migrates from confluence/clouddocs to unified external_links

import django.db.models.deletion
from django.db import migrations, models


def populate_documentation_space(apps, schema_editor):
    """
    Migrate Project FKs from old confluence_space/google_drive_folder to new documentation_space.
    This is idempotent - safe to run multiple times.
    """
    Project = apps.get_model("projects", "Project")
    ExternalResource = apps.get_model("external_links", "ExternalResource")

    # Check if old columns still exist using Django's introspection API (works with SQLite, MySQL, PostgreSQL)
    connection = schema_editor.connection

    # Check if table exists first
    tables = connection.introspection.table_names()
    has_project_table = "projects_project" in tables

    # Check if old columns exist
    has_confluence_col = False
    has_drive_col = False

    if has_project_table:
        with connection.cursor() as cursor:
            columns = {col.name for col in connection.introspection.get_table_description(cursor, "projects_project")}
            has_confluence_col = "confluence_space_id" in columns
            has_drive_col = "google_drive_folder_id" in columns

    if not has_confluence_col and not has_drive_col:
        print("Old FK columns not found - skipping Project FK migration")
        print("(This is expected if columns were already dropped)")
        return

    migrated = 0
    skipped = 0
    no_old_fk = 0

    # Use raw SQL to read FK values since historical model may not have the fields
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT id, confluence_space_id, google_drive_folder_id, documentation_space_id FROM projects_project"
        )
        project_rows = cursor.fetchall()

    for project_id, confluence_space_id, google_drive_folder_id, documentation_space_id in project_rows:
        # Skip if already migrated (idempotent check)
        if documentation_space_id is not None:
            skipped += 1
            continue

        # Try confluence_space first
        if has_confluence_col and confluence_space_id:
            # Find matching ExternalResource by URL (system_name detected from URL during creation)
            try:
                with connection.cursor() as cursor:
                    cursor.execute("SELECT url FROM confluence_space WHERE id = %s", [confluence_space_id])
                    row = cursor.fetchone()
                    if row:
                        space_url = row[0]
                        # Search by URL only - the URL might exist as doc_page if it was
                        # also in confluence_page table (same URL in multiple legacy tables)
                        external = ExternalResource.objects.filter(url=space_url).first()
                        if external:
                            Project.objects.filter(id=project_id).update(documentation_space=external)
                            migrated += 1
                            continue
            except Exception as e:
                print(f"Warning: Could not migrate confluence_space for project {project_id}: {e}")

        # Try google_drive_folder if confluence didn't work
        if has_drive_col and google_drive_folder_id:
            try:
                with connection.cursor() as cursor:
                    cursor.execute("SELECT url FROM clouddocs_drivefolder WHERE id = %s", [google_drive_folder_id])
                    row = cursor.fetchone()
                    if row:
                        folder_url = row[0]
                        # Search by URL only - the URL might exist as doc_page if it was
                        # also in confluence_page table (same URL in multiple legacy tables)
                        external = ExternalResource.objects.filter(url=folder_url).first()
                        if external:
                            Project.objects.filter(id=project_id).update(documentation_space=external)
                            migrated += 1
                            continue
            except Exception as e:
                print(f"Warning: Could not migrate google_drive_folder for project {project_id}: {e}")

        # Neither confluence_space nor google_drive_folder was set
        if not confluence_space_id and not google_drive_folder_id:
            no_old_fk += 1

    print(
        f"Projects: Migrated {migrated} documentation links, skipped {skipped} (already migrated), {no_old_fk} had no old FK"
    )


def reverse_migration(apps, schema_editor):
    """Reverse migration - clear documentation_space FKs."""
    Project = apps.get_model("projects", "Project")
    updated = Project.objects.filter(documentation_space__isnull=False).update(documentation_space=None)
    print(f"Cleared documentation_space for {updated} projects")


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_project_project_leader"),
        ("external_links", "0003_migrate_legacy_docs"),
    ]

    operations = [
        # Step 1: Add new unified documentation_space field
        migrations.AddField(
            model_name="project",
            name="documentation_space",
            field=models.ForeignKey(
                blank=True,
                help_text="Project documentation workspace (Confluence, Google Drive, Benchling, etc.)",
                limit_choices_to={"resource_type": "doc_space"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_doc_spaces",
                to="external_links.externalresource",
            ),
        ),
        # Step 2: Migrate data from old columns to new column
        migrations.RunPython(populate_documentation_space, reverse_migration),
        # Step 3 & 4: Drop old foreign key constraints and columns
        # Note: These are intentionally noops. The columns can be removed manually in production
        # after verifying the migration. SQLite doesn't support DROP FOREIGN KEY and this
        # migration is designed to be idempotent and work across database backends.
        # migrations.RunSQL(
        #     sql="ALTER TABLE `projects_project` DROP FOREIGN KEY `projects_project_confluence_space_id_9b48fcb7_fk_confluenc`;",
        #     reverse_sql=migrations.RunSQL.noop,
        # ),
        # migrations.RunSQL(
        #     sql="ALTER TABLE `projects_project` DROP FOREIGN KEY `projects_project_google_drive_folder__ecb7c954_fk_clouddocs`;",
        #     reverse_sql=migrations.RunSQL.noop,
        # ),
        # migrations.RunSQL(
        #     sql="ALTER TABLE `projects_project` DROP COLUMN `confluence_space_id`;",
        #     reverse_sql=migrations.RunSQL.noop,
        # ),
        # migrations.RunSQL(
        #     sql="ALTER TABLE `projects_project` DROP COLUMN `google_drive_folder_id`;",
        #     reverse_sql=migrations.RunSQL.noop,
        # ),
    ]
