nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.1.cjs

# packageExtensions are used here to patch unmet peer dependencies that arise due to
# how idetik is used as a Git submodule and Yarn workspace.
# We intentionally avoid modifying the submodule's package.json to keep it clean and reusable.
# These extensions ensure correct dependency resolution in this parent project only.
packageExtensions:
  "@types/react-dom@*":
    peerDependencies:
      "@types/react": "*"
  autoprefixer@*:
    peerDependencies:
      postcss: "*"
