site_name: Embrella
site_dir: docs_build
dev_addr: '127.0.0.1:8001'
repo_url: 'https://github.com/chanzuckerberg/embrella'
repo_name: 'chanzuckerberg/embrella'
copyright: '2026, Biohub'
theme:
  name: material
  variant: modern
  logo: assets/embrella_logo.png
  palette:
    - media: "(prefers-color-scheme)"
      primary: indigo
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: lucide/moon
        name: Switch system preference
  features:
    - content.code.copy
extra_css:
  - stylesheets/extras.css
extra_javascript:
  - javascripts/video.js
nav:
  - Home: index.md
  - User Guide:
      - Overview: 'userguide/overview.md'
      - Grid Logging: 'userguide/gridlogging.md'
      - Grid Inventory: 'userguide/gridinventory.md'
      - Create Imaging Session: 'userguide/createimagingsession.md'
      - Launch Processing: 'userguide/launchprocessing.md'
      - View Metadata: 'userguide/metadataapp.md'
      - Review Tomograms: 'userguide/reviewapp.md'
  - Contributing:
      - Getting Started: 'contributing/gettingstarted.md'
      - Container Layout: 'contributing/containers.md'
      - Managing Environment Secrets: 'contributing/environments.md'
      - Running/Deploying: 'contributing/deployment.md'
      - Version Control/Release Convention: 'contributing/convention.md'
