site_name: Embrella
site_dir: docs_build
dev_addr: '127.0.0.1:8001'
repo_url: 'https://github.com/chanzuckerberg/embrella'
repo_name: 'chanzuckerberg/embrella'
copyright: '2026, Biohub'
theme:
  name: material
  variant: modern
  palette:
    - scheme: biohub
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
extra_css:
  - stylesheets/extras.css
nav:
  - Home: index.md
  - Tutorials:
      - User Guide: 'tutorials/userguide.md'
  - Contributing:
      - Getting Started: 'contributing/gettingstarted.md'
      - Container Layout: 'contributing/containers.md'
      - Managing Environment Secrets: 'contributing/environments.md'
      - Running/Deploying: 'contributing/deployment.md'
      - Updating Documentation: 'contributing/documentation.md'
      - Version Control/Release Convention: 'contributing/convention.md'
