"""
Django settings for umbrella project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

from corsheaders.defaults import default_headers as default_cors_headers

BASE_DIR = Path(__file__).resolve().parent.parent  # Build paths inside the project like this: BASE_DIR / 'subdir'.
ENVIRONMENT = os.getenv("DJANGO_ENV", "development")
DEBUG = ENVIRONMENT == "development"

# When True, all SSH/SFTP cluster access is disabled and fails fast instead of
# hanging on the connect timeout. Used for public-facing demo servers that have
# no cluster access
SSH_DISABLED = os.getenv("SSH_DISABLED") == "True"


def run_with_args(args):
    try:
        return subprocess.check_output(args, cwd=BASE_DIR).decode("utf-8")
    except (FileNotFoundError, subprocess.CalledProcessError):
        return "N/A"


# TODO: Below GIT vars are not used except in legacy html. Plan to remove
GIT_HASH = run_with_args(["git", "rev-parse", "--short", "HEAD"])
GIT_BRANCH = run_with_args(["git", "rev-parse", "--abbrev-ref", "HEAD"])
START_TIME = datetime.now(tz=timezone.utc).astimezone(ZoneInfo("America/Los_Angeles")).strftime("%Y-%m-%d %H:%M %z")

LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/Los_Angeles"
USE_I18N = True
USE_TZ = True

WSGI_APPLICATION = "umbrella.wsgi.application"
ROOT_URLCONF = "umbrella.urls"
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_URL = "/static/"

DOCUMENTATION_ROOT = Path(BASE_DIR).resolve().parent / "docs_build"
DOCUMENTATION_HTML_ROOT = DOCUMENTATION_ROOT
DOCUMENTATION_XSENDFILE = False

# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
mysql_db = {
    "ENGINE": "django.db.backends.mysql",
    "NAME": os.getenv("MYSQL_NAME", ""),
    "USER": os.getenv("MYSQL_USER", ""),
    "PASSWORD": os.getenv("MYSQL_PWD", ""),
    "HOST": os.getenv("MYSQL_HOST", "127.0.0.1"),
    "PORT": os.getenv("MYSQL_PORT", "3306"),
}

sqlite_db = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": BASE_DIR / "db.sqlite3",
}

DATABASES = {
    "default": sqlite_db if ENVIRONMENT == "development" and os.getenv("USE_MYSQL") != "True" else mysql_db,
}

INSTALLED_APPS = [
    "external_links",
    "django_object_actions",
    "jazzmin",
    "cryo_grids",
    "depositions",
    "projects",
    "workflow",
    "tem",
    "stores",
    "custom",
    "processes",
    "accounts",
    "people",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "corsheaders",
    "drf_spectacular",
    "django_q",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "umbrella.middleware.APIAuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "umbrella.middleware.FixLoginRedirectMiddleware",  # Fix login redirects to use HTTP_REFERER
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/min",
        "user": "1000/min",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Embrella API",
    "DESCRIPTION": "API documentation for Embrella project",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": True,
}

JAZZMIN_SETTINGS = {
    "show_ui_builder": False,
    "show_version": False,
    "show_view_site": True,
    "show_sidebar": True,
    "navigation_expanded": False,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        # App groups
        "cryo_grids": "fas fa-snowflake",
        "tem": "fas fa-microscope",
        "django_google_sso": "fas fa-key",
        "processes": "fas fa-cogs",
        "workflow": "fas fa-project-diagram",
        "projects": "fas fa-folder-open",
        "stores": "fas fa-database",
        "accounts": "fas fa-id-badge",
        "external_links": "fas fa-link",
        # Notable models
        "cryo_grids.dewar": "fas fa-warehouse",
        "cryo_grids.cane": "fas fa-grip-lines-vertical",
        "cryo_grids.puck": "fas fa-hockey-puck",
        "cryo_grids.cryogrid": "fas fa-th",
        "cryo_grids.sample": "fas fa-vial",
        "cryo_grids.specimen": "fas fa-dna",
        "tem.microscope": "fas fa-microscope",
        "tem.msisession": "fas fa-calendar-check",
        "tem.sessionplan": "fas fa-clipboard-list",
        "stores.path": "fas fa-folder",
        "stores.staticpath": "fas fa-thumbtack",
        "stores.pathtype": "fas fa-tags",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "site_logo": "jazzmin/img/biohub_logo_white.svg",
    "login_logo": "jazzmin/img/biohub-logo.svg",
    "site_icon": "jazzmin/img/favicon.png",
    # Match the admin to the Next.js app palette
    "custom_css": "admin_theme/custom.css",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "default_theme_mode": "auto",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-outline-primary",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

# --- django-allauth (Google SSO) ---------------------------------------------
# Provider credentials are sourced from env vars (reusing the existing
# GOOGLE_SSO_* names) so no DB SocialApp row / admin step is required.
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_SSO_CLIENT_ID"),
            "secret": os.environ.get("GOOGLE_SSO_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKCE_ENABLED": True,
    }
}
# Signup off by default so self-hosters keep open, domain-gated SSO signup.
EMBRELLA_DISABLE_SIGNUP = os.environ.get("EMBRELLA_DISABLE_SIGNUP") == "True"
# Google emails are trusted; skip allauth's signup/email-confirm interstitials.
SOCIALACCOUNT_AUTO_SIGNUP = not EMBRELLA_DISABLE_SIGNUP
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True  # match existing local users by email
ACCOUNT_LOGOUT_ON_GET = True
SOCIALACCOUNT_ADAPTER = "umbrella.adapters.UmbrellaSocialAccountAdapter"
ACCOUNT_ADAPTER = "umbrella.adapters.UmbrellaAccountAdapter"
# Restrict SSO to these email domains
SSO_ALLOWED_DOMAINS = ["czii.org", "czbiohub.org", "biohub.org"]

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "*.czbiohub.org",
    "umbrella.czbiohub.org",
    "umbrella-dev.czbiohub.org",
    "host.containers.internal",
    "host.docker.internal",
    "nginx",
]
ALLOWED_DOMAINS = ["czii.org", "czbiohub.org"]
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://umbrella.czbiohub.org",
    "https://umbrella-dev.czbiohub.org",
    # HTTP versions for staging (if not behind HTTPS termination)
    "http://umbrella.czbiohub.org",
    "http://umbrella-dev.czbiohub.org",
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = default_cors_headers + ("Access-Control-Allow-Origin",)
CORS_EXPOSE_HEADERS = ["Access-Control-Allow-Origin", "Content-Type", "Location"]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://umbrella.czbiohub.org",
    "https://umbrella-dev.czbiohub.org",
    # HTTP versions for staging (if not behind HTTPS termination)
    "http://umbrella.czbiohub.org",
    "http://umbrella-dev.czbiohub.org",
]

# Argus/k8s ingress host, injected by the argus-config subchart from
# global.ingress.host. Lets Django accept requests and trust CSRF behind the
# cluster ingress without hardcoding the (per-stack) staging hostname. No-op for
# self-hosters, who won't have this env var set.
_ARGUS_INGRESS_HOST = os.environ.get("__ARGUS_STACK_INGRESS_HOST")
if _ARGUS_INGRESS_HOST:
    ALLOWED_HOSTS.append(_ARGUS_INGRESS_HOST)
    CSRF_TRUSTED_ORIGINS.append(f"https://{_ARGUS_INGRESS_HOST}")
    CORS_ALLOWED_ORIGINS.append(f"https://{_ARGUS_INGRESS_HOST}")
    # TLS terminates at the ingress; trust the forwarded proto so redirects,
    # secure cookies, and CSRF see https and the external host.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

# File-server base-URL allowlist. stores.Cluster.http_base_url is admin-editable
# and is both embedded in the frontend (image/zarr/config URLs) and fetched
# server-side, so a tampered value is a content-injection + SSRF risk. Only these
# origins (scheme://host[:port], comma-separated) may be used as a cluster base
# URL. Empty = no restriction (backwards compatible); set it in staging/prod.
FILESERVER_ALLOWED_HOSTS = [
    h.strip().rstrip("/") for h in os.environ.get("FILESERVER_ALLOWED_HOSTS", "").split(",") if h.strip()
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_AGE = 1209600

# Django-Q2 Configuration
Q_CLUSTER = {
    "name": "umbrella",
    "workers": 4,
    "recycle": 500,
    "timeout": 300,  # 5 minutes for SSH operations
    "retry": 360,  # Retry failed tasks after 6 minutes
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",  # Use Django ORM as broker
    "catch_up": False,  # Don't run missed scheduled tasks
}
