"""
Django settings for umbrella project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import subprocess
from datetime import datetime
from pathlib import Path

import pytz
from corsheaders.defaults import default_headers as default_cors_headers

BASE_DIR = Path(__file__).resolve().parent.parent  # Build paths inside the project like this: BASE_DIR / 'subdir'.
ENVIRONMENT = os.getenv("DJANGO_ENV", "development")
DEBUG = ENVIRONMENT == "development"

def run_with_args(args):
    try:
        return subprocess.check_output(args, cwd=BASE_DIR).decode("utf-8")
    except (FileNotFoundError, subprocess.CalledProcessError):
        return "N/A"

GIT_HASH = run_with_args(["git", "rev-parse", "--short", "HEAD"])
GIT_BRANCH = run_with_args(["git", "rev-parse", "--abbrev-ref", "HEAD"])
START_TIME = datetime.now(tz=pytz.utc).astimezone(pytz.timezone("US/Pacific")).strftime("%Y-%m-%d %H:%M %z")

LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/Los_Angeles"
USE_I18N = True
USE_TZ = True

WSGI_APPLICATION = "umbrella.wsgi.application"
ROOT_URLCONF = "umbrella.urls"
LOGIN_URL = "/admin/login/"
LOGIN_REDIRECT_URL = "/"
LOGIN_REQUIRED_IGNORE_PATHS = [
    r"^/admin/login/*",
    r"^/admin/logout/*",
    r"^/google_sso/*",
    r"^/static/*",
    r"^/login/*",
    r"^/copick/v1/.*",
]
# Exempt user info endpoint - frontend should handle 401 and redirect
LOGIN_REQUIRED_IGNORE_VIEW_NAMES = [
    'user_info',
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    #os.path.join(Path(BASE_DIR).resolve().parent, "docs_build"),
]
STATIC_URL = "/static/"

DOCUMENTATION_ROOT = Path(BASE_DIR).resolve().parent / 'docs_build'
DOCUMENTATION_HTML_ROOT = DOCUMENTATION_ROOT
DOCUMENTATION_XSENDFILE = False

# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
mysql_db = {
    "ENGINE": "django.db.backends.mysql",
    "NAME": os.getenv("MYSQL_NAME", ""),
    "USER": os.getenv("MYSQL_USER", ""),
    "PASSWORD": os.getenv("MYSQL_PWD", ""),
    "HOST": os.getenv("MYSQL_HOST", "127.0.0.1"),
    "PORT": os.getenv("MYSQL_PORT", "3306"),
}

sqlite_db = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": BASE_DIR / "db.sqlite3",
}

DATABASES = {
    "default": sqlite_db if ENVIRONMENT == "development" and os.getenv("USE_MYSQL") != "True" else mysql_db,
}

INSTALLED_APPS = [
    "external_links",
    "django_object_actions",
    "jazzmin",
    "cryo_grids",
    "projects",
    "workflow",
    "tem",
    "stores",
    #'social_django',
    "custom",
    "processes",
    "users",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django_google_sso",
    "corsheaders",
    "drf_spectacular",
    "django_q",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "umbrella.middleware.APIAuthenticationMiddleware",  # Return 401 for API requests - MUST come before LoginRequiredMiddleware
    #"django.contrib.auth.middleware.LoginRequiredMiddleware",
    "login_required.middleware.LoginRequiredMiddleware",
    "umbrella.middleware.FixLoginRedirectMiddleware",  # Fix login redirects to use HTTP_REFERER
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    #"umbrella.middleware.SetNextParameterMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [Path(BASE_DIR).resolve().parent],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Umbrella API',
    'DESCRIPTION': 'API documentation for Umbrella project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
}

JAZZMIN_SETTINGS = {
    # Other Jazzmin settings...
    "show_ui_builder": True,  # Disable the UI Builder
    "copyright": "CZII",
    "show_version": False,
    "show_view_site": True,
    "show_sidebar": True,
    "site_logo": "jazzmin/img/biohub-logo.svg",
    "login_logo": "jazzmin/img/biohub-logo.svg",
    # "topmenu_links": [
    #     # Url that gets reversed (Permissions can be added)
    #     {"name": "Go back to the startup page", "url": "/umbrella", "permissions": ["auth.view_user"]},
    # ],
}

GOOGLE_SSO_CLIENT_ID = os.environ.get("GOOGLE_SSO_CLIENT_ID")
GOOGLE_SSO_PROJECT_ID = os.environ.get("GOOGLE_SSO_PROJECT_ID")
GOOGLE_SSO_CLIENT_SECRET = os.environ.get("GOOGLE_SSO_CLIENT_SECRET")
GOOGLE_SSO_ALLOWABLE_DOMAINS = ["umbrella.czbiohub.org", "127.0.0.1:8000", "127.0.0.1", "czii.org"]
GOOGLE_SSO_PRE_LOGIN_CALLBACK = "umbrella.hooks.pre_login_callback"
GOOGLE_SSO_ALLOWED_DOMAINS = ["czii.org", "czbiohub.org"]
GOOGLE_SSO_SESSION_COOKIE_AGE = 1209600  # 14 days — match SESSION_COOKIE_AGE
# Configure Google SSO to respect the 'next' parameter for redirects
GOOGLE_SSO_SAVE_BASIC_GOOGLE_INFO = False

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-_p$6q-6t2x(33d^u=hfgb@fycd0bp^8zy0dwfo@lonrl^zf+4*")
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "*.czbiohub.org", "umbrella.czbiohub.org", "umbrella-dev.czbiohub.org", "host.containers.internal", "host.docker.internal", "nginx"]
ALLOWED_DOMAINS = ["czii.org", "czbiohub.org"]
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://umbrella.czbiohub.org",
    "https://umbrella-dev.czbiohub.org",
    # HTTP versions for staging (if not behind HTTPS termination)
    "http://umbrella.czbiohub.org",
    "http://umbrella-dev.czbiohub.org",
]
# IMPORTANT: Do not enable CORS_ORIGIN_ALLOW_ALL in production!
# CORS_ORIGIN_ALLOW_ALL = True  # REMOVED: This overrides CORS_ALLOWED_ORIGINS
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
# ]
CORS_ALLOW_HEADERS = default_cors_headers + ("Access-Control-Allow-Origin",)
CORS_EXPOSE_HEADERS = ["Access-Control-Allow-Origin", "Content-Type", "Location"]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://umbrella.czbiohub.org",
    "https://umbrella-dev.czbiohub.org",
    # HTTP versions for staging (if not behind HTTPS termination)
    "http://umbrella.czbiohub.org",
    "http://umbrella-dev.czbiohub.org",
]
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    # 'django_google_sso.backends.GoogleSSOAuthBackend',
]
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_AGE = 1209600
# SESSION_COOKIE_SAMESITE = None


# Django-Q2 Configuration
Q_CLUSTER = {
    'name': 'umbrella',
    'workers': 4,
    'recycle': 500,
    'timeout': 300,  # 5 minutes for SSH operations
    'retry': 360,  # Retry failed tasks after 6 minutes
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',  # Use Django ORM as broker
    'catch_up': False,  # Don't run missed scheduled tasks
}
