"""
Custom API views for DenoisET processor.

Provides processor-specific endpoints for:
- Dynamic form field options (available AreTomo3 runs)
- Processor metadata (denoising guidance, examples)
"""

from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from processes.models import ProcRun
from tem.models import MsiSession


@require_http_methods(["GET"])
def get_dynamic_options(request, session_id: str = None) -> JsonResponse:
    """
    Get dynamic dropdown options for DenoisET form fields.

    Args:
        request: Django HTTP request
        session_id: Optional MSI session ID for session-specific options

    Returns:
        JsonResponse with field options:
        {
            "aretomo3_runs": [
                {"value": "run001", "label": "run001", "description": "..."},
                ...
            ]
        }
    """
    options = {}

    # Get available AreTomo3 runs for the session
    if session_id:
        try:
            session = MsiSession.objects.get(name=session_id)

            # Find all ProcRuns for this session with AreTomo3 plan
            # AreTomo3 runs are in the "czii-live" processing plan
            from processes.models import ProcPlan

            try:
                aretomo3_plan = ProcPlan.objects.get(name="czii-live")
                aretomo_runs = ProcRun.objects.filter(
                    msi_session=session,
                    proc_plan=aretomo3_plan,
                ).order_by("-created_at")

                options["aretomo3_runs"] = [
                    {
                        "value": run.name,
                        "label": run.name,
                        "description": f"Created {run.created_at.strftime('%Y-%m-%d %H:%M')}",
                    }
                    for run in aretomo_runs
                ]

            except ProcPlan.DoesNotExist:
                options["aretomo3_runs"] = []

        except MsiSession.DoesNotExist:
            options["aretomo3_runs"] = []

    return JsonResponse(
        {
            "success": True,
            "options": options,
        }
    )


@require_http_methods(["GET"])
def get_processor_metadata(request) -> JsonResponse:
    """
    Get DenoisET processor metadata for UI display.

    Returns help text, parameter examples, and documentation links.

    Args:
        request: Django HTTP request

    Returns:
        JsonResponse with processor metadata
    """
    return JsonResponse(
        {
            "success": True,
            "metadata": {
                "help_text": (
                    "DenoisET applies deep learning-based denoising to tomograms generated by AreTomo3. "
                    "It uses a trained convolutional neural network to reduce noise while preserving "
                    "structural features, improving the quality of downstream analysis."
                ),
                "category": "Post-processing",
                "examples": [
                    {
                        "title": "Standard denoising with lysosome model",
                        "description": "Apply DenoisET lysosome model to AreTomo3 output",
                        "params": {
                            "aretomo_run": "run001",
                            "model_name": "lysosome.pth",
                            "live_denoising": False,
                        },
                    },
                    {
                        "title": "Live denoising for ongoing session",
                        "description": "Monitor AreTomo3 output directory and denoise new tomograms as they appear",
                        "params": {
                            "aretomo_run": "run001",
                            "model_name": "lysosome.pth",
                            "live_denoising": True,
                        },
                    },
                ],
                "docs_url": "https://github.com/czimaginginstitute/DenoisET",
                "parameter_notes": {
                    "aretomo_run": "Select the AreTomo3 run containing tomograms to denoise. Must be completed.",
                    "model_name": "Choose DenoisET model trained on a specific sample type (lysosome, minicell, synaptosome, or cilia).",
                    "live_denoising": "Enable to automatically denoise new tomograms as they are generated. Useful for ongoing sessions.",
                },
                "input_requirements": {
                    "format": "MRC tomogram files from AreTomo3",
                    "min_size": "512x512x100 pixels",
                    "note": "Tomograms should be binned appropriately before denoising for best results",
                },
            },
        }
    )
