# Generated by Django 5.0.2 on 2024-05-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0002_alter_space_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(default='BD01', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sample prep notes', max_length=32)),
                ('url', models.URLField()),
            ],
            options={
                'unique_together': {('name', 'url')},
            },
        ),
    ]
