services:
  db:
    image: mariadb:10.5.22
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'devaccount'
      MARIADB_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mariadb_data:
