# Generated by Django 5.0.2 on 2024-05-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledoc', '0002_alter_drivefolder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivefolder',
            name='name',
            field=models.CharField(default='BD01', max_length=32, unique=True),
        ),
    ]
