# Generated by Django 5.2.7 on 2026-05-04 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_table_if_missing(apps, schema_editor):
    """Create the pinned table only when it doesn't already exist.

    Fresh DBs: the table is absent, so we create it (equivalent to a plain
    ``CreateModel``). Existing staging/prod DBs that were migrated under the old
    ``users`` app label already have ``users_userclustercredentials`` — there we
    no-op, so applying ``accounts.0001_initial`` no longer fails with
    ``(1050, "Table ... already exists")``.

    We pull the model from the *global* app registry rather than the ``apps``
    argument: this is an initial migration, so the historical state has no
    ``accounts`` app yet. For the very first create the historical and current
    model definitions are identical, so using the real model is safe.
    """
    from django.apps import apps as global_apps

    model = global_apps.get_model("accounts", "UserClusterCredentials")
    table = model._meta.db_table
    if table not in schema_editor.connection.introspection.table_names():
        schema_editor.create_model(model)


def drop_table(apps, schema_editor):
    from django.apps import apps as global_apps

    model = global_apps.get_model("accounts", "UserClusterCredentials")
    schema_editor.delete_model(model)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0012_copick_url_pathtype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Keep Django's model *state* identical to a normal CreateModel, but make
        # the *database* side conditional so the pinned table isn't re-created on
        # DBs that already have it (carried over from the old `users` app label).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="UserClusterCredentials",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("username", models.CharField(max_length=64)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "cluster",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="stores.cluster",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="cluster_credentials",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name_plural": "User cluster credentials",
                        "db_table": "users_userclustercredentials",
                        "unique_together": {("user", "cluster")},
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(create_table_if_missing, drop_table),
            ],
        ),
    ]
