from django.contrib import admin

from .models import *
# Register your models here.
admin.site.register(MetaKey)
admin.site.register(Task)
admin.site.register(ProcSoftware)
admin.site.register(ProcPlan)
admin.site.register(Pipe)
admin.site.register(PipeJoint)
admin.site.register(PipeInPlan)
admin.site.register(GlobalParam)
admin.site.register(PipeParam)
admin.site.register(ProcRun)
admin.site.register(RunGlobalValue)
admin.site.register(RunPipeValue)
admin.site.register(RunPipeData)
admin.site.register(Frames)
admin.site.register(RawTiltSeries)
admin.site.register(TiltAngles)
admin.site.register(Ctf)
admin.site.register(Alignment)
admin.site.register(ReconMethod)
admin.site.register(TomogramVoxelSpacing)
admin.site.register(Tomograms)
admin.site.register(TomoPostProcessMethod)
admin.site.register(AnnotationMethod)
admin.site.register(Annotation)
admin.site.register(ParticleGallery)
admin.site.register(Review)
admin.site.register(ReviewTomogram)
