from django.urls import path
from . import views

app_name = "workflow"

urlpatterns = [
    path("get_aretomo3", views.get_aretomo3_json, name='json_aretomo3'),
    path("run", views.custom_run_workflow_page, name='custom_run_workflow_page'),
    path("", views.custom_workflow_page, name='custom_workflow'),
    path("denoiset_run", views.cutom_run_denoise_workflow_page, name="custom_denoise_workflow"),
    path("copick_run", views.cutom_run_create_and_import_copick_page, name="custom_copick_workflow"),
    path("membraneseg_run", views.custom_run_membraneseg_page, name="custom_membraneseg_workflow"),
    path("octopi_run", views.custom_run_octopi_page, name="custom_octopi_workflow"),
    path("cancel", views.custom_workflow_cancel, name='cancle workflow jobs'),
    path("track", views.custom_workflow_track, name='track workflow jobs'),
    path("logs", views.custom_workflow_logs, name='job logs'),
    path("run_aretomo3", views.run_aretomo3, name='run_aretomo3'),
    path("cancel_jobs", views.cancel_jobs, name='cancel_jobs'),
    path("track_jobs", views.track_jobs, name='track_jobs'),
    path("user_info", views.user_info, name='user_details'),
    path("get_msi_session_list", views.get_msi_session_list, name='get all msi session name'),
    path("run_advanced_aretomo3", views.run_aretomo3_advanced, name='run_advanced_aretomo3'),
    path("run_denoiset", views.run_denoiset, name='run denoiset'),
    path("aretomo3_params", views.get_msi_params_list, name='get parameters'),
    path("denoise_params", views.get_msi_params_list, name='get denoise parameters'),
    path("copick_params", views.get_msi_params_list, name='get copick parameters'),
    path("octopi_params", views.get_msi_params_list, name='get octopi parameters'),
    path("job_logs", views.get_job_logs, name='fetching logs'),
    path("dashboard/", views.dashboard, name='dashboard'),
    path('data/', views.workflow_get_data, name='dashboard_data'),
    path("status/", views.status_check_api, name='workflow status'),
    path('metadata/api/v1/summary/', views.get_metadata_summary, name='get_metadata_summary'),
    path('metadata/api/v1/data/', views.get_metadata_viz_data, name='get_metadata_viz_data'),
    path('get_plan_id', views.get_plan_id, name='get_plan_id'),
    path('get_msisession_id', views.get_msisession_id, name='get_msisession_id'),
    path('trigger_syncer/', views.trigger_syncer, name='trigger_syncer'),
    path("run-create-copick/", views.run_create_copick, name="run_create_copick"),
    path("run-import-tomogram-copick/", views.run_import_tomogram_copick, name="run_import_tomogram_copick"),
    path("template_maps/", views.get_template_map_json, name="template_maps"),
    path("run-copick-add-object/", views.run_copick_add_object, name="run_add_object_copick"),
    path("api/tomo-combos", views.get_tomo_combos_json, name="get_tomo_combos_json"),
]