# Generated by Django 5.2.7 on 2026-06-15 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cryo_grids", "0036_sample_cell_component_name_sample_cell_name_and_more"),
        ("tem", "0023_alter_magnification_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositionAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "copick_kind",
                    models.CharField(
                        choices=[
                            ("picks", "Picks"),
                            ("segmentations", "Segmentations"),
                            ("meshes", "Meshes"),
                        ],
                        max_length=30,
                    ),
                ),
                ("copick_ref", models.CharField(max_length=256)),
                ("object_id", models.CharField(blank=True, max_length=40)),
                ("object_name", models.CharField(blank=True, max_length=128)),
                ("object_description", models.TextField(blank=True)),
                ("object_state", models.CharField(blank=True, max_length=40)),
                ("object_count", models.IntegerField(blank=True, null=True)),
                ("annotation_method", models.CharField(blank=True, max_length=256)),
                ("annotation_software", models.CharField(blank=True, max_length=256)),
                ("annotation_publication", models.TextField(blank=True)),
                (
                    "method_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Manual"),
                            ("automated", "Automated"),
                            ("hybrid", "Hybrid"),
                            ("simulated", "Simulated"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ground_truth_status", models.BooleanField(default=False)),
                (
                    "is_visualization_default",
                    models.BooleanField(
                        default=False,
                        help_text="should this annotation be the DEFAULT shown in the portal viewer?",
                    ),
                ),
                (
                    "is_selected",
                    models.BooleanField(
                        default=True,
                        help_text="should this annotation be INCLUDED in the deposition",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Assigned by reservation service",
                        null=True,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                ("sample_preparation", models.TextField(blank=True)),
                ("grid_preparation", models.TextField(blank=True)),
                ("assay_label", models.CharField(blank=True, max_length=40)),
                ("assay_ontology_id", models.CharField(blank=True, max_length=64)),
                ("is_authors_same_as_deposition", models.BooleanField(default=True)),
                (
                    "authors_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Only used when is_authors_same_as_deposition=False. Same shape as Deposition.authors_json.",
                    ),
                ),
                ("dataset_publications", models.TextField(blank=True)),
                ("related_database_entries", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        help_text="The biological sample this dataset describes. Sample identity fields (organism, tissue, cell_type, cell_strain, cell_component, sample_type) live on cryo_grids.Sample.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="datasets",
                        to="cryo_grids.sample",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DatasetFunding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("funding_agency_name", models.CharField(max_length=256)),
                ("grant_id", models.CharField(blank=True, max_length=32)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding",
                        to="depositions.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposition_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Assigned by reservation service",
                        null=True,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitting", "Submitting"),
                            ("submitted", "Submitted"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("deposition_publications", models.TextField(blank=True)),
                ("related_database_entries", models.TextField(blank=True)),
                (
                    "authors_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {author_id, is_primary, is_corresponding, author_list_order}. author_id will FK to users.Author once that model exists.",
                    ),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitter_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depositions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="dataset",
            name="deposition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="depositions.deposition",
            ),
        ),
        migrations.CreateModel(
            name="DepositionAnnotationMethodLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("documentation", "Documentation"),
                            ("models_weights", "Models/Weights"),
                            ("other", "Other"),
                            ("source_code", "Source Code"),
                            ("website", "Website"),
                        ],
                        max_length=40,
                    ),
                ),
                ("link", models.URLField(max_length=1024)),
                ("custom_name", models.CharField(blank=True, max_length=128)),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="method_links",
                        to="depositions.depositionannotation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepositionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prep_slurm_job_id",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "push_slurm_job_id",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("prep_submitted", "Prep Submitted"),
                            ("prep_running", "Prep Running"),
                            ("prep_completed", "Prep Completed"),
                            ("push_submitted", "Push Submitted"),
                            ("push_running", "Push Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("log_excerpt", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deposition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job",
                        to="depositions.deposition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepositionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aretomo_run_name", models.CharField(blank=True, max_length=20)),
                (
                    "denoise_run_name",
                    models.CharField(
                        blank=True,
                        help_text="Blank means denoise was skipped",
                        max_length=20,
                    ),
                ),
                ("subset_csv_path", models.CharField(blank=True, max_length=1024)),
                ("selected_copick_runs", models.JSONField(blank=True, default=list)),
                ("last_autofill_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_autofill_duration_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="depositions.dataset",
                    ),
                ),
                (
                    "msi_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposition_sessions",
                        to="tem.msisession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("dataset", "msi_session")},
            },
        ),
        migrations.AddField(
            model_name="depositionannotation",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="depositions.depositionsession",
            ),
        ),
        migrations.CreateModel(
            name="TiltseriesMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acceleration_voltage", models.FloatField(blank=True, null=True)),
                (
                    "spherical_aberration_constant",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "microscope_manufacturer",
                    models.CharField(blank=True, max_length=256),
                ),
                ("microscope_model", models.CharField(blank=True, max_length=256)),
                (
                    "microscope_energy_filter",
                    models.CharField(blank=True, max_length=256),
                ),
                (
                    "microscope_image_corrector",
                    models.CharField(blank=True, max_length=256),
                ),
                (
                    "microscope_phase_plate",
                    models.CharField(blank=True, max_length=256),
                ),
                ("camera_manufacturer", models.CharField(blank=True, max_length=40)),
                ("camera_model", models.CharField(blank=True, max_length=40)),
                ("tilt_min", models.FloatField(blank=True, null=True)),
                ("tilt_max", models.FloatField(blank=True, null=True)),
                ("tilt_step", models.FloatField(blank=True, null=True)),
                ("tilting_scheme", models.CharField(blank=True, max_length=40)),
                ("tilt_axis", models.FloatField(blank=True, null=True)),
                ("total_flux", models.FloatField(blank=True, null=True)),
                (
                    "data_acquisition_software",
                    models.CharField(blank=True, max_length=40),
                ),
                ("pixel_spacing", models.FloatField(blank=True, null=True)),
                ("is_aligned", models.BooleanField(blank=True, null=True)),
                (
                    "aligned_tiltseries_binning",
                    models.IntegerField(blank=True, null=True),
                ),
                ("binning_from_frames", models.FloatField(blank=True, null=True)),
                (
                    "tilt_series_quality",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                ("autofill_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiltseries_metadata",
                        to="depositions.depositionsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TomogramMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voxel_spacing", models.FloatField(blank=True, null=True)),
                ("ctf_corrected", models.BooleanField(blank=True, null=True)),
                (
                    "fiducial_alignment_status",
                    models.CharField(blank=True, max_length=40),
                ),
                ("reconstruction_method", models.CharField(blank=True, max_length=40)),
                (
                    "reconstruction_software",
                    models.CharField(blank=True, max_length=40),
                ),
                ("processing", models.CharField(blank=True, max_length=40)),
                ("processing_software", models.CharField(blank=True, max_length=40)),
                ("is_visualization_default", models.BooleanField(default=False)),
                ("autofill_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tomogram_metadata",
                        to="depositions.depositionsession",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="depositionannotation",
            unique_together={("session", "copick_kind", "copick_ref")},
        ),
    ]
