# Generated by Django 5.2.15 on 2026-08-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depositions", "0002_dataset_tomogram_subset_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositionsession",
            name="subset_selection",
            field=models.JSONField(
                blank=True,
                help_text="Draft custom-subset selection; written to the cluster at submit.",
                null=True,
            ),
        ),
    ]
