# Generated by Django 5.2.16 on 2026-08-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depositions", "0003_depositionsession_subset_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositionsession",
            name="subset_filename",
            field=models.CharField(
                blank=True,
                help_text="Original name of the uploaded subset file, for display in the wizard.",
                max_length=255,
            ),
        ),
    ]
