# Generated by Django 5.2.16 on 2026-08-26 21:34

import django.db.models.deletion
from django.db import migrations, models


def backfill_flavor(apps, schema_editor):
    # Rows from the OneToOne era get flavor="" from AddField. There was one row per session, so
    # assign them the denoised default (matches deposition_prep's visualization default)
    TomogramMetadata = apps.get_model("depositions", "TomogramMetadata")
    TomogramMetadata.objects.filter(flavor="").update(flavor="denoised")


class Migration(migrations.Migration):

    dependencies = [
        ("depositions", "0004_depositionsession_subset_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="tomogrammetadata",
            name="flavor",
            field=models.CharField(
                blank=True,
                choices=[("denoised", "Denoised"), ("filtered", "Filtered")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="tomogrammetadata",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tomogram_metadata",
                to="depositions.depositionsession",
            ),
        ),
        migrations.RunPython(backfill_flavor, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="tomogrammetadata",
            unique_together={("session", "flavor")},
        ),
    ]
