# Generated by Django 5.2.16 on 2026-10-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depositions", "0005_tomogrammetadata_flavor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetjob",
            name="staged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
