# Generated by Django 5.2.16 on 2026-10-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depositions", "0006_datasetjob_staged_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetjob",
            name="cluster_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
