# Generated by Django 5.0.2 on 2024-03-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivefolder',
            name='name',
            field=models.CharField(choices=[('BD01', 'BD01 Human Organelle Library'), ('TRD05', 'TRD05 Data Integration'), ('TRD??', 'TRD?? ML Challenge')], default='BD01', max_length=6, unique=True),
        ),
    ]
