# Generated by Django 5.2.7 on 2025-11-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("doc_space", "Documentation Space"),
                            ("doc_page", "Documentation Page"),
                        ],
                        help_text="Type of documentation resource",
                        max_length=20,
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        help_text="Documentation system name (e.g., 'Confluence', 'Google Drive', 'Benchling', 'Notion')",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this resource", max_length=100
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="Full URL to the documentation resource"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="System-specific fields (e.g., {'space_id': 'CHOL'} for Confluence)",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Resource",
                "verbose_name_plural": "External Resources",
                "indexes": [
                    models.Index(
                        fields=["resource_type", "system_name"],
                        name="external_li_resourc_3b1375_idx",
                    )
                ],
                "unique_together": {("resource_type", "name", "system_name")},
            },
        ),
    ]
