# Generated by Django 5.2.7 on 2025-11-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_links", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="externalresource",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="externalresource",
            name="url",
            field=models.URLField(
                help_text="Full URL to the documentation resource", unique=True
            ),
        ),
    ]
