# Generated by Django 5.0.2 on 2024-08-06 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0008_annotationmethod_annotation_particlegallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="method",
        ),
        migrations.AlterField(
            model_name="annotation",
            name="annotation_method",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="processes.annotationmethod"),
        ),
    ]
