# Generated by Django 5.0.6 on 2024-11-01 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0011_alter_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="procrun",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
