# Generated by Django 5.0.6 on 2024-12-03 00:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0012_procrun_created_at"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="annotation",
        #     name="created_at",
        #     field=models.DateTimeField(
        #         auto_now_add=True, default=django.utils.timezone.now
        #     ),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name="annotation",
        #     name="updated_at",
        #     field=models.DateTimeField(auto_now=True),
        # ),
        # migrations.AddField(
        #     model_name="procrun",
        #     name="updated_at",
        #     field=models.DateTimeField(auto_now=True),
        # ),
    ]
