# Generated by Django 5.1.2 on 2024-12-04 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0013_annotation_created_at_annotation_updated_at_and_more"),
        ("processes", "0013_procrun_updated_at"),
    ]

    operations = []
