# Generated by Django 5.0.6 on 2024-12-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0014_merge_20241204_1141"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="notes",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
