# Generated by Django 5.0.6 on 2025-01-16 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0015_annotation_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="annotation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
