# Generated by Django 5.0.6 on 2025-05-13 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0017_joblog"),
        ("tem", "0021_alter_magnification_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "review_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("review_name", models.CharField(max_length=255)),
                ("review_type", models.CharField(max_length=100)),
                ("run_id", models.CharField(max_length=100)),
                ("reconstruction_type", models.CharField(max_length=100)),
                ("total_count", models.IntegerField(default=0)),
                ("reviewed_count", models.IntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("save_path", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requestor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tem.msisession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewTomogram",
            fields=[
                (
                    "tomogram_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reasons", models.JSONField(blank=True, default=list)),
                ("object_labels", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_tomograms",
                        to="processes.review",
                    ),
                ),
            ],
            options={
                "unique_together": {("review", "tomogram_id")},
            },
        ),
    ]
