# Generated by Django 5.0.6 on 2025-05-15 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0018_review_reviewtomogram"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewtomogram",
            name="position_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reviewtomogram",
            name="quality",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("uncertain", "Uncertain"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
