# Generated by Django 5.0.6 on 2025-05-20 22:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0019_reviewtomogram_position_id_and_more"),
        ("tem", "0021_alter_magnification_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="session",
        ),
        migrations.AddField(
            model_name="review",
            name="msi_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_tomograms",
                to="tem.msisession",
            ),
        ),
        migrations.AddField(
            model_name="reviewtomogram",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewtomogram",
            name="reconstruction_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reviewtomogram",
            name="run_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reviewtomogram",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_tomograms",
                to="tem.msisession",
            ),
        ),
        migrations.AlterField(
            model_name="reviewtomogram",
            name="quality",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("uncertain", "Uncertain"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewtomogram",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_tomograms",
                to="processes.review",
            ),
        ),
    ]
