# Generated by Django 5.2 on 2025-05-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0020_remove_review_session_review_msi_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='objects_of_interest',
            field=models.TextField(null=True),
        ),
    ]
