# Generated by Django 5.0.6 on 2025-06-02 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0021_review_objects_of_interest_alter_review_msi_session"),
        ("tem", "0021_alter_magnification_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="msi_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_tomograms",
                to="tem.msisession",
            ),
        ),
    ]
