# Generated by Django 5.2.7 on 2025-10-31 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0022_alter_review_msi_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="procsoftware",
            name="cluster",
            field=models.CharField(
                choices=[("czii", "CZII"), ("bruno", "Bruno")],
                default="czii",
                help_text="Default cluster for job submission",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="procsoftware",
            name="processor_class",
            field=models.CharField(
                blank=True,
                help_text='Processor class name (e.g., "aretomo3" maps to AreTomo3Processor)',
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="procsoftware",
            name="script_directory",
            field=models.CharField(
                blank=True,
                help_text="Remote script directory (e.g., /hpc/projects/.../scripts)",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="procsoftware",
            name="callback_function",
            field=models.CharField(
                default="run_aretomo3",
                help_text="Deprecated: use processor_class",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PipeExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "script_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pipe_in_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processes.pipeinplan",
                    ),
                ),
                (
                    "proc_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipe_executions",
                        to="processes.procrun",
                    ),
                ),
            ],
            options={
                "ordering": ["pipe_in_plan__step"],
                "unique_together": {("proc_run", "pipe_in_plan")},
            },
        ),
    ]
