# Generated by Django 5.2.7 on 2025-11-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "processes",
            "0026_procsoftware_cluster_procsoftware_processor_class_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="procsoftware",
            old_name="cluster",
            new_name="default_cluster",
        ),
        migrations.AddField(
            model_name="procsoftware",
            name="allowed_clusters",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of cluster IDs this software can run on (e.g., ["czii", "bruno"]). Empty means all clusters allowed.',
            ),
        ),
    ]
