# Generated by Django 5.2.7 on 2025-11-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0027_add_cluster_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeexecution",
            name="script_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
