# Generated by Django 5.2.7 on 2025-11-05 06:04

from django.db import migrations


def fix_denoiset_copick_dependencies(apps, schema_editor):
    """
    Fix denoiset and copick to use parameter-based input selection instead of PipeJoints.

    Changes:
    1. Update 'denoise' ProcSoftware to have processor_class='denoiset'
    2. Delete duplicate 'denoiset' ProcSoftware entry if it exists
    3. Remove PipeJoints for denoiset and copick (they use parameter-based input selection)
    """
    ProcSoftware = apps.get_model('processes', 'ProcSoftware')
    PipeJoint = apps.get_model('processes', 'PipeJoint')
    PipeInPlan = apps.get_model('processes', 'PipeInPlan')

    # 1. Update 'denoise' ProcSoftware to have processor_class='denoiset'
    try:
        denoise_sw = ProcSoftware.objects.get(name='denoise')
        denoise_sw.processor_class = 'denoiset'
        denoise_sw.default_cluster = 'czii'
        denoise_sw.allowed_clusters = ['czii', 'bruno']
        denoise_sw.save()
        print(f"✓ Updated denoise ProcSoftware: processor_class='denoiset'")
    except ProcSoftware.DoesNotExist:
        print("⚠ 'denoise' ProcSoftware not found - skipping update")

    # 2. Delete duplicate 'denoiset' ProcSoftware if it exists
    try:
        denoiset_sw = ProcSoftware.objects.get(name='denoiset')
        denoiset_sw.delete()
        print(f"✓ Deleted duplicate 'denoiset' ProcSoftware")
    except ProcSoftware.DoesNotExist:
        print("✓ No duplicate 'denoiset' ProcSoftware found")

    # 3. Remove PipeJoints for denoiset
    try:
        denoise_pip = PipeInPlan.objects.filter(
            plan__name='czii-denoise',
            pipe__software__name='denoise'
        ).first()

        if denoise_pip:
            denoise_joints = PipeJoint.objects.filter(pipe_in_plan=denoise_pip)
            count = denoise_joints.count()
            if count > 0:
                denoise_joints.delete()
                print(f"✓ Deleted {count} PipeJoint(s) for denoiset")
            else:
                print("✓ No PipeJoints for denoiset")
    except Exception as e:
        print(f"⚠ Could not remove denoiset PipeJoints: {e}")

    # 4. Remove PipeJoints for copick
    try:
        copick_pip = PipeInPlan.objects.filter(
            plan__name='czii-copick',
            pipe__software__name='copick'
        ).first()

        if copick_pip:
            copick_joints = PipeJoint.objects.filter(pipe_in_plan=copick_pip)
            count = copick_joints.count()
            if count > 0:
                copick_joints.delete()
                print(f"✓ Deleted {count} PipeJoint(s) for copick")
            else:
                print("✓ No PipeJoints for copick")
    except Exception as e:
        print(f"⚠ Could not remove copick PipeJoints: {e}")


def reverse_fix(apps, schema_editor):
    """
    Reverse the migration (note: this won't perfectly restore the old state).

    We can restore the ProcSoftware changes, but recreating PipeJoints
    would require knowing the exact configuration, which varies by environment.
    """
    ProcSoftware = apps.get_model('processes', 'ProcSoftware')

    # Reverse: Remove processor_class from denoise
    try:
        denoise_sw = ProcSoftware.objects.get(name='denoise')
        denoise_sw.processor_class = None
        denoise_sw.default_cluster = None
        denoise_sw.allowed_clusters = None
        denoise_sw.save()
        print("✓ Reversed denoise ProcSoftware changes")
    except ProcSoftware.DoesNotExist:
        print("⚠ 'denoise' ProcSoftware not found - skipping reverse")

    print("⚠ Note: PipeJoints were not recreated. If needed, restore from backup.")


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0028_add_script_content_to_pipe_execution"),
    ]

    operations = [
        migrations.RunPython(
            fix_denoiset_copick_dependencies,
            reverse_code=reverse_fix,
        ),
    ]
