# Generated by Django 5.2.7 on 2025-11-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0030_add_job_logs_to_pipe_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="procsoftware",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this processor is currently active in the codebase",
            ),
        ),
    ]
