# Generated by Django 5.2.7 on 2025-12-11 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0031_procsoftware_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SLURM job ID (for legacy syncers without PipeExecution)",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("init", "Initialization"),
                            ("sync_start", "Sync Started"),
                            ("sync_complete", "Sync Completed"),
                            ("file_found", "File Found"),
                            ("tomogram_created", "Tomogram Created"),
                            ("tomogram_deleted", "Tomogram Deleted"),
                            ("review_updated", "Review Updated"),
                            ("job_check", "Job Status Check"),
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("stopped", "Syncer Stopped"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="Human-readable log message")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured data (e.g., file paths, counts, error details)",
                    ),
                ),
                (
                    "syncer_type",
                    models.CharField(
                        blank=True,
                        help_text="Syncer class name (e.g., AretomoSyncer, DenoiseSyncer)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "session_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("run_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "pipe_execution",
                    models.ForeignKey(
                        blank=True,
                        help_text="PipeExecution this log belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syncer_logs",
                        to="processes.pipeexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["pipe_execution", "-timestamp"],
                        name="processes_s_pipe_ex_b8d57a_idx",
                    ),
                    models.Index(
                        fields=["job_id", "-timestamp"],
                        name="processes_s_job_id_e55a76_idx",
                    ),
                    models.Index(
                        fields=["session_name", "run_id", "-timestamp"],
                        name="processes_s_session_570e4e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncerProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(blank=True, db_index=True, max_length=32, null=True),
                ),
                ("syncer_type", models.CharField(max_length=50)),
                ("session_name", models.CharField(max_length=100)),
                ("run_id", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_heartbeat", models.DateTimeField(auto_now=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "pipe_execution",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syncer_process",
                        to="processes.pipeexecution",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["job_id"], name="processes_s_job_id_154c3e_idx"),
                    models.Index(fields=["status"], name="processes_s_status_905b5e_idx"),
                ],
            },
        ),
    ]
