# Generated by Django 5.2.7 on 2025-12-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0032_add_syncer_logging"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeexecution",
            name="syncer_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether a JobStatusSyncer is actively monitoring this job",
            ),
        ),
    ]
