# Generated by Django 5.2.7 on 2025-12-12 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("processes", "0033_add_syncer_active_to_pipeexecution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FilesystemSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster",
                    models.CharField(
                        choices=[("czii", "CZII"), ("bruno", "Bruno")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "base_path",
                    models.CharField(help_text="Root path that was surveyed", max_length=500),
                ),
                (
                    "job_id",
                    models.CharField(blank=True, db_index=True, max_length=32, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("running", "Running"),
                            ("processing", "Processing Results"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "results_parquet_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to Parquet file on cluster containing file-level details",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("total_files", models.BigIntegerField(default=0)),
                ("total_directories", models.BigIntegerField(default=0)),
                ("total_size_bytes", models.BigIntegerField(default=0)),
                (
                    "size_by_user",
                    models.JSONField(blank=True, default=dict, help_text='{"username": bytes, ...}'),
                ),
                (
                    "count_by_user",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"username": file_count, ...}',
                    ),
                ),
                (
                    "size_by_origin",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"app_generated": bytes, ...}',
                    ),
                ),
                (
                    "count_by_origin",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"app_generated": file_count, ...}',
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectorySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster", models.CharField(db_index=True, max_length=16)),
                ("path", models.CharField(help_text="Directory path", max_length=500)),
                ("file_count", models.IntegerField(default=0)),
                ("total_size_bytes", models.BigIntegerField(default=0)),
                (
                    "owner_username",
                    models.CharField(
                        blank=True,
                        help_text="Most common owner",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("owner_uid", models.IntegerField(blank=True, null=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("app_generated", "App Generated"),
                            ("synced_from_czii", "Synced from CZII"),
                            ("user_created", "User Created"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "preserve_status",
                    models.CharField(
                        choices=[
                            ("unset", "Unset"),
                            ("preserve", "Preserve"),
                            ("delete", "Delete"),
                            ("review", "Needs Review"),
                        ],
                        db_index=True,
                        default="unset",
                        max_length=20,
                    ),
                ),
                ("status_updated_at", models.DateTimeField(blank=True, null=True)),
                ("status_notes", models.TextField(blank=True, null=True)),
                (
                    "depth",
                    models.IntegerField(default=0, help_text="Directory depth from base_path"),
                ),
                ("newest_file_mtime", models.DateTimeField(blank=True, null=True)),
                ("oldest_file_mtime", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "status_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="directory_status_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directory_summaries",
                        to="processes.filesystemsurvey",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.AddIndex(
            model_name="filesystemsurvey",
            index=models.Index(fields=["cluster", "status"], name="processes_f_cluster_e92a3d_idx"),
        ),
        migrations.AddIndex(
            model_name="filesystemsurvey",
            index=models.Index(fields=["cluster", "-created_at"], name="processes_f_cluster_b1e040_idx"),
        ),
        migrations.AddIndex(
            model_name="directorysummary",
            index=models.Index(
                fields=["cluster", "origin", "preserve_status"],
                name="processes_d_cluster_4ec084_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="directorysummary",
            index=models.Index(fields=["survey", "depth"], name="processes_d_survey__f93e40_idx"),
        ),
        migrations.AddIndex(
            model_name="directorysummary",
            index=models.Index(fields=["cluster", "path"], name="processes_d_cluster_65d811_idx"),
        ),
        migrations.AddIndex(
            model_name="directorysummary",
            index=models.Index(fields=["owner_username"], name="processes_d_owner_u_77b1a6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="directorysummary",
            unique_together={("survey", "path")},
        ),
    ]
