# Generated by Django 5.2.7 on 2026-04-23 17:52

import django.db.models.deletion
from django.db import migrations, models


def backfill_czii(apps, schema_editor):
    Review = apps.get_model("processes", "Review")
    Cluster = apps.get_model("stores", "Cluster")
    try:
        czii = Cluster.objects.get(cluster_id="czii")
    except Cluster.DoesNotExist:
        return
    Review.objects.filter(cluster__isnull=True).update(cluster=czii)


def unbackfill(apps, schema_editor):
    Review = apps.get_model("processes", "Review")
    Review.objects.update(cluster=None)


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0036_fix_membraneseg_processor"),
        ("stores", "0010_seed_clusters"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="stores.cluster",
            ),
        ),
        migrations.RunPython(backfill_czii, unbackfill),
    ]
