# Generated by Django 5.2.15 on 2026-08-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0037_review_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='procplan',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Human-readable label for the UI. Falls back to name when blank.', max_length=64),
        ),
    ]
