# Generated by Django 5.2.16 on 2026-08-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0037_review_cluster'),
        ('stores', '0017_alter_datakind_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='input',
            field=models.ManyToManyField(related_name='datakind_in_input', to='stores.datakind'),
        ),
    ]
