# Generated by Django 5.2.15 on 2026-08-13 17:29

from posixpath import basename, dirname

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_storage_dirnames(apps, schema_editor):
    """
    One-time seed of ProcSoftware.storage_dirname; maintained by hand afterwards.

    Derived from script_directory, which BaseProcessor builds as
    `<processing base>/<dirname>/scripts` -- so its grandparent segment is the
    directory the software actually writes into. That catches the cases where
    the name differs: both copick sub-processors point at `.../copick/scripts`,
    and `denoise` (whose processor_class is `denoiset`) at `.../denoise/scripts`.
    """
    ProcSoftware = apps.get_model("processes", "ProcSoftware")

    for software in ProcSoftware.objects.all():
        if software.storage_dirname:
            continue
        from_scripts = basename(dirname((software.script_directory or "").rstrip("/")))
        software.storage_dirname = from_scripts or software.name
        software.save(update_fields=["storage_dirname"])


def clear_storage_dirnames(apps, schema_editor):
    ProcSoftware = apps.get_model("processes", "ProcSoftware")
    ProcSoftware.objects.update(storage_dirname="")


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0039_consolidate_procsoftware_by_processor_class'),
        ('tem', '0023_alter_magnification_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procsoftware',
            name='storage_dirname',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Directory on the cluster this software writes into, used to group the Storage Explorer. Usually the same as name, but not always: both copick sub-processors write into 'copick'. Maintained by hand in the admin; blank falls back to name.", max_length=64),
        ),
        migrations.CreateModel(
            name='StorageDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(db_index=True, max_length=16)),
                ('path_prefix', models.CharField(help_text='Session or run directory this decision covers', max_length=512)),
                ('status', models.CharField(choices=[('unset', 'Unset'), ('preserve', 'Preserve'), ('delete', 'Delete'), ('review', 'Needs Review')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cluster', 'path_prefix'],
                'indexes': [models.Index(fields=['cluster', 'path_prefix'], name='processes_s_cluster_d0fba5_idx')],
                'unique_together': {('cluster', 'path_prefix')},
            },
        ),
        migrations.CreateModel(
            name='StorageRunSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(db_index=True, max_length=16)),
                ('software', models.CharField(db_index=True, help_text="Depth-1 segment, e.g. 'aretomo3'", max_length=64)),
                ('session_name', models.CharField(db_index=True, help_text='Depth-2 segment; may not be a known MsiSession', max_length=255)),
                ('run_name', models.CharField(blank=True, default='', help_text='Depth-3 segment. Empty means files directly under the session directory.', max_length=64)),
                ('path_prefix', models.CharField(help_text='The directory this leaf covers', max_length=512)),
                ('directory_count', models.IntegerField(default=0)),
                ('file_count', models.BigIntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('newest_file_mtime', models.DateTimeField(blank=True, null=True)),
                ('oldest_file_mtime', models.DateTimeField(blank=True, null=True)),
                ('owner_username', models.CharField(blank=True, default='', help_text='Most common owner', max_length=64)),
                ('built_at', models.DateTimeField(auto_now=True)),
                ('msi_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_run_summaries', to='tem.msisession')),
                ('proc_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_run_summaries', to='processes.procrun')),
                ('proc_software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_run_summaries', to='processes.procsoftware')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_summaries', to='processes.filesystemsurvey')),
            ],
            options={
                'verbose_name_plural': 'storage run summaries',
                'ordering': ['session_name', 'software', 'run_name'],
                'indexes': [models.Index(fields=['survey', 'session_name'], name='processes_s_survey__a1393a_idx'), models.Index(fields=['survey', 'software'], name='processes_s_survey__4512ad_idx'), models.Index(fields=['survey', '-total_size_bytes'], name='processes_s_survey__cae7fe_idx')],
                'unique_together': {('survey', 'software', 'session_name', 'run_name')},
            },
        ),
        migrations.RunPython(seed_storage_dirnames, clear_storage_dirnames),
    ]
