# Generated by Django 5.2.16 on 2026-08-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0042_procsoftware_processing_directory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procsoftware',
            name='processing_directory',
            field=models.CharField(blank=True, default='', help_text="Remote root this software's runs are written under, scanned by the syncers (e.g., /hpc/projects/.../aretomo3).", max_length=256),
        ),
    ]
