# Generated by Django 5.2.16 on 2026-08-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0043_sync_processing_directory_help_text'),
        ('tem', '0025_sessionplanpathbinding_file_pattern'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewtomogram',
            constraint=models.UniqueConstraint(fields=('session', 'run_id', 'reconstruction_type', 'position_id'), name='uniq_reviewtomogram_identity'),
        ),
    ]
