# Generated by Django 5.2.16 on 2026-08-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0044_reviewtomogram_uniq_reviewtomogram_identity"),
        # 0022 seeds the shared templates the removed columns' readers now resolve
        # against -- guarantee they exist before the columns drop.
        ("stores", "0022_processing_root_templates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procsoftware',
            name='processing_directory',
        ),
        migrations.RemoveField(
            model_name='procsoftware',
            name='script_directory',
        ),
        migrations.AddField(
            model_name='procsoftware',
            name='processing_root',
            field=models.ForeignKey(blank=True, help_text="Directory template for this software's runs, when they live outside the standard tree. Blank = the shared processing_root template.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processing_root_of', to='stores.pathtype'),
        ),
        migrations.AddField(
            model_name='procsoftware',
            name='script_dir',
            field=models.ForeignKey(blank=True, help_text="Directory template for this software's uploaded scripts, when they live outside the standard tree. Blank = the shared script_dir template.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='script_dir_of', to='stores.pathtype'),
        ),
    ]
