# Generated by Django 5.2.16 on 2026-08-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0045_remove_procsoftware_processing_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtomogram',
            name='file_path',
            field=models.CharField(blank=True, default='', help_text='discovered file path relative to the run directory', max_length=255),
        ),
    ]
