# Generated by Django 5.2.16 on 2026-08-27 23:23
"""ProcSoftware declares its output naming; the code-shipped label contract dies.

Binds the canonical rec FilePattern (seeded by stores/0021) to aretomo3 and denoiset --
the two softwares whose volumes the syncers discover. The old lookup hardcoded the row's
label in workflow/syncers.py (REC_PATTERN_LABEL); the label string appears here one last
time, as data, and is display-only afterwards.
"""

from django.db import migrations, models

REC_LABEL = "{position}_Vol.zarr"
SYNCED_SOFTWARE = ("aretomo3", "denoiset")


def bind_rec_pattern(apps, schema_editor):
    FilePattern = apps.get_model("stores", "FilePattern")
    ProcSoftware = apps.get_model("processes", "ProcSoftware")

    pattern = FilePattern.objects.filter(data_kind__data_type="rec", label=REC_LABEL).first()
    if pattern is None:
        return  # fresh install without the 0021 seed; the accessor is loud when unbound

    for software in ProcSoftware.objects.filter(processor_class__in=SYNCED_SOFTWARE):
        software.output_patterns.add(pattern)


def unbind_rec_pattern(apps, schema_editor):
    ProcSoftware = apps.get_model("processes", "ProcSoftware")
    for software in ProcSoftware.objects.filter(processor_class__in=SYNCED_SOFTWARE):
        software.output_patterns.clear()


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0047_backfill_reviewtomogram_file_path"),
        ("stores", "0024_zarr_url_ends_at_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="procsoftware",
            name="output_patterns",
            field=models.ManyToManyField(
                blank=True,
                help_text="How this software names its output files, at most one pattern per data kind (e.g. rec volumes, thumbnails, metrics CSV). Read by the syncers and job templates through BaseProcessor.get_output_pattern().",
                related_name="output_of",
                to="stores.filepattern",
            ),
        ),
        migrations.RunPython(bind_rec_pattern, unbind_rec_pattern),
    ]
