# Generated by Django 5.2.16 on 2026-09-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0048_procsoftware_output_patterns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runglobalvalue',
            name='param',
        ),
        migrations.RemoveField(
            model_name='pipeparam',
            name='key',
        ),
        migrations.RemoveField(
            model_name='pipeparam',
            name='pipe',
        ),
        migrations.RemoveField(
            model_name='runpipevalue',
            name='param',
        ),
        migrations.RemoveField(
            model_name='runglobalvalue',
            name='run',
        ),
        migrations.RemoveField(
            model_name='runpipevalue',
            name='run',
        ),
        migrations.DeleteModel(
            name='GlobalParam',
        ),
        migrations.DeleteModel(
            name='MetaKey',
        ),
        migrations.DeleteModel(
            name='PipeParam',
        ),
        migrations.DeleteModel(
            name='RunGlobalValue',
        ),
        migrations.DeleteModel(
            name='RunPipeValue',
        ),
    ]
