# Generated by Django 5.2.16 on 2026-09-03 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0050_init_copick_scan_procplan'),
        ('stores', '0024_zarr_url_ends_at_directory'),
        ('tem', '0025_sessionplan_name_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=dict, help_text='{parameter: value}. Keys must exist in the processor schema. null clears the default.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('cluster', models.ForeignKey(blank=True, help_text='Blank = any cluster.', null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.cluster')),
                ('proc_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_defaults', to='processes.procsoftware')),
                ('scope', models.ForeignKey(blank=True, help_text='Blank = any microscope.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tem.microscope')),
                ('software', models.ForeignKey(blank=True, help_text='Blank = any acquisition software.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tem.software')),
            ],
            options={
                'verbose_name_plural': 'parameter defaults',
            },
        ),
    ]
