# Generated by Django 5.0.2 on 2024-03-03 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cryo_grids', '0002_rename_session_cryogrid_freezing_session_and_more'),
        ('projects', '0002_alter_project_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Falcon4i', max_length=20, unique=True)),
                ('root_dir', models.CharField(max_length=80, unique=True)),
                ('frame_format', models.CharField(max_length=20)),
                ('initial_frame_base_dir', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImagingWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaging_mode', models.CharField(choices=[('tem', 'TEM'), ('stem', 'STEM')], max_length=20)),
                ('workflow', models.CharField(choices=[('scrn', 'Grid Screening'), ('sngl', 'Single Tilt SPA'), ('tomo', 'Tomography'), ('ptyc', 'Ptychography'), ('idpc', 'iDPC')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Microscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Krios1', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('root_dir', models.CharField(help_text='absolute path to access images from all sessions', max_length=80, unique=True)),
                ('add_user_dir', models.BooleanField(help_text='need to insert username division before session')),
                ('parent_image_dir', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_image_pattern', models.CharField(blank=True, max_length=20, null=True)),
                ('sum_image_dir', models.CharField(blank=True, max_length=20, null=True)),
                ('sum_image_pattern', models.CharField(blank=True, max_length=20, null=True)),
                ('grid_atlas_image_dir', models.CharField(blank=True, max_length=20, null=True)),
                ('grid_atlas_image_pattern', models.CharField(blank=True, max_length=20, null=True)),
                ('frame_root_dir', models.CharField(blank=True, help_text='absolute path to access frame directory from all sessions', max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_format', models.CharField(blank=True, max_length=10, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.camera')),
                ('imaging_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.imagingworkflow')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.microscope')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tem.software')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
                ('grid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cryo_grids.cryogrid')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session_plan', models.ManyToManyField(to='tem.sessionplan')),
            ],
        ),
    ]
