# Generated by Django 5.0.2 on 2024-03-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tem", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="software",
            old_name="root_dir",
            new_name="image_root_dir",
        ),
        migrations.AddField(
            model_name="software",
            name="frame_dir",
            field=models.CharField(
                blank=True, help_text="relative path to access frames under session", max_length=80, null=True
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="grid_atlas_image_dir",
            field=models.CharField(
                blank=True, help_text="relative path to access grid atlas image under session", max_length=80, null=True
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="grid_atlas_image_pattern",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="software",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="software",
            name="parent_image_dir",
            field=models.CharField(
                blank=True, help_text="relative path to access parent images under session", max_length=80, null=True
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="parent_image_pattern",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="software",
            name="sum_image_dir",
            field=models.CharField(
                blank=True, help_text="relative path to access parent images under session", max_length=80, null=True
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="sum_image_pattern",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
