# Generated by Django 5.0.3 on 2024-04-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionhistory',
            old_name='session',
            new_name='session_id',
        ),
    ]
