# Generated by Django 5.0.3 on 2024-04-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0002_rename_session_sessionhistory_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
