# Generated by Django 5.0.3 on 2024-04-05 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0002_session_updated_at_sessionhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionhistory',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tem.session'),
        ),
    ]
