# Generated by Django 5.0.3 on 2024-04-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0003_alter_sessionplan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionhistory',
            old_name='session_id',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagingworkflow',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microscope',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
