# Generated by Django 5.0.2 on 2024-05-08 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "__first__"),
        ("tem", "0004_alter_software_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionplan",
            name="frame_format",
        ),
        migrations.RemoveField(
            model_name="software",
            name="add_user_dir",
        ),
        migrations.RemoveField(
            model_name="software",
            name="frame_dir",
        ),
        migrations.RemoveField(
            model_name="software",
            name="frame_root_dir",
        ),
        migrations.RemoveField(
            model_name="software",
            name="grid_atlas_image_dir",
        ),
        migrations.RemoveField(
            model_name="software",
            name="grid_atlas_image_pattern",
        ),
        migrations.RemoveField(
            model_name="software",
            name="image_root_dir",
        ),
        migrations.RemoveField(
            model_name="software",
            name="parent_image_dir",
        ),
        migrations.RemoveField(
            model_name="software",
            name="parent_image_pattern",
        ),
        migrations.RemoveField(
            model_name="software",
            name="sum_image_dir",
        ),
        migrations.RemoveField(
            model_name="software",
            name="sum_image_pattern",
        ),
        migrations.AddField(
            model_name="session",
            name="frames",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="frames", to="stores.path"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="mdocs",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mdocs", to="stores.path"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="sums",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sums", to="stores.path"
            ),
        ),
        migrations.AddField(
            model_name="software",
            name="atlas",
            field=models.ForeignKey(
                help_text="path pattern to access grid atlas image for viewing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atlas_type",
                to="stores.pathtype",
            ),
        ),
        migrations.AddField(
            model_name="software",
            name="frames",
            field=models.ForeignKey(
                help_text="path pattern to access frames",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="frames_type",
                to="stores.pathtype",
            ),
        ),
        migrations.AddField(
            model_name="software",
            name="mdocs",
            field=models.ForeignKey(
                help_text="path pattern to access mdocs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mdocs_type",
                to="stores.pathtype",
            ),
        ),
        migrations.AddField(
            model_name="software",
            name="parents",
            field=models.ForeignKey(
                help_text="path pattern to access parent images for viewing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parents_type",
                to="stores.pathtype",
            ),
        ),
        migrations.AddField(
            model_name="software",
            name="sums",
            field=models.ForeignKey(
                help_text="path pattern to access 0 tilt projection thumbnail image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sums_type",
                to="stores.pathtype",
            ),
        ),
    ]
