# Generated by Django 5.0.2 on 2024-05-25 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0004_alter_staticpath_data_type"),
        ("tem", "0007_screensessiongroup_screensession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="atlas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atlas",
                to="stores.path",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="frames",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="frames",
                to="stores.path",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="mdocs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mdocs",
                to="stores.path",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="parents",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parents",
                to="stores.path",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="sums",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sums",
                to="stores.path",
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="atlas",
            field=models.ForeignKey(
                blank=True,
                help_text="path pattern to access grid atlas image for viewing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atlas_type",
                to="stores.pathtype",
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="frames",
            field=models.ForeignKey(
                blank=True,
                help_text="path pattern to access frames",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="frames_type",
                to="stores.pathtype",
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="mdocs",
            field=models.ForeignKey(
                blank=True,
                help_text="path pattern to access mdocs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mdocs_type",
                to="stores.pathtype",
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="parents",
            field=models.ForeignKey(
                blank=True,
                help_text="path pattern to access parent images for viewing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parents_type",
                to="stores.pathtype",
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="sums",
            field=models.ForeignKey(
                blank=True,
                help_text="path pattern to access 0 tilt projection thumbnail image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sums_type",
                to="stores.pathtype",
            ),
        ),
    ]
