# Generated by Django 5.0.6 on 2024-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tem", "0008_alter_session_atlas_alter_session_frames_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="message",
            field=models.TextField(
                blank=True,
                default="Please see the file directory below and store accordingly",
                max_length=255,
                null=True,
            ),
        ),
    ]
