# Generated by Django 5.0.6 on 2024-06-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tem", "0012_rename_screensession_atlassession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msisession",
            name="atlas_session",
            field=models.ForeignKey(
                blank=True,
                help_text="link a seperate grid screen atlas if exists",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tem.atlassession",
            ),
        ),
    ]
