# Generated by Django 5.0.6 on 2024-06-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0014_msisession_created_at_msisession_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msisession',
            name='user',
        ),
    ]
