# Generated by Django 5.0.6 on 2024-06-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0016_msisession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msisession',
            name='user',
        ),
    ]
