# Generated by Django 5.0.2 on 2024-08-08 19:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tem", "0018_msisession_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="microscope",
            name="cs",
            field=models.FloatField(default=2.7, help_text="Spherical abberation constant in mm"),
        ),
        migrations.CreateModel(
            name="Magnification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "nominal_mag",
                    models.PositiveIntegerField(default=50000, help_text="Nominal mag displayed on the scope"),
                ),
                ("index", models.PositiveIntegerField(default=0, help_text="Base 0 index of list order")),
                ("scope", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tem.microscope")),
            ],
        ),
        migrations.CreateModel(
            name="CalibratedPixelSize",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pixel_spacing", models.FloatField(default=4.0, help_text="Pixel spacing in Angstroms")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("current", models.BooleanField(default=True, help_text="Is this the current calibration ?")),
                ("camera", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tem.camera")),
                ("mag", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tem.magnification")),
            ],
        ),
    ]
