# Generated by Django 5.0.2 on 2024-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tem", "0019_microscope_cs_magnification_calibratedpixelsize"),
    ]

    operations = [
        migrations.AddField(
            model_name="magnification",
            name="mode",
            field=models.CharField(default="SA", help_text="projection mode", max_length=8, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="magnification",
            unique_together={("scope", "mode", "index")},
        ),
    ]
