# Generated by Django 5.2.7 on 2026-03-05 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tem", "0021_alter_magnification_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibratedpixelsize",
            name="current",
        ),
        migrations.AddField(
            model_name="calibratedpixelsize",
            name="calibrated_at",
            field=models.DateTimeField(blank=True, help_text="When the calibration was performed", null=True),
        ),
        migrations.AddField(
            model_name="msisession",
            name="magnification",
            field=models.ForeignKey(
                blank=True,
                help_text="Magnification used for this session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tem.magnification",
            ),
        ),
    ]
