# Generated by Django 5.2.7 on 2026-03-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tem", "0022_remove_calibratedpixelsize_current_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="magnification",
            unique_together={("scope", "mode", "nominal_mag")},
        ),
    ]
