# Generated by Django 5.2.16 on 2026-08-21 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_pathtype_cluster'),
        ('tem', '0023_alter_magnification_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='version',
            field=models.CharField(blank=True, default='', help_text="A version that lays files out differently is a separate row. So is a distinct protocol -- name it compoundly, e.g. 'Tomo5 dose-symmetric'.", max_length=32),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='software',
            unique_together={('name', 'version')},
        ),
        migrations.CreateModel(
            name='SessionPlanPathBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('frames', 'frames'), ('sums', 'sums'), ('mdocs', 'mdocs'), ('parents', 'parents'), ('atlas', 'atlas')], max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('path_type', models.ForeignKey(blank=True, help_text='Directory template for this role on this plan. Blank falls back to the software default.', null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.pathtype')),
                ('session_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_bindings', to='tem.sessionplan')),
            ],
            options={
                'unique_together': {('session_plan', 'role')},
            },
        ),
    ]
