# Generated by Django 5.2.16 on 2026-09-02 18:33

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0024_software_version_and_path_bindings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplan',
            name='name_prefix',
            field=models.CharField(blank=True, default='', help_text="Lowercase letters put in front of suggested MSI session names, so sessions from this scope/software pair are told apart at a glance. Blank for none. E.g. 's' suggests s26jun08a; blank suggests 26jun08a.", max_length=4, validators=[django.core.validators.RegexValidator(re.compile('^[a-z]*$'), 'Lowercase letters only.')]),
        ),
    ]
