# Generated by Django 5.2.16 on 2026-08-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_filepattern_pathtype_file_pattern'),
        ('tem', '0024_software_version_alter_software_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplanpathbinding',
            name='file_pattern',
            field=models.ForeignKey(blank=True, help_text="Filename convention for this role on this plan. Blank falls back to the resolved directory's own.", null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.filepattern'),
        ),
    ]
