# Generated by Django 5.2.16 on 2026-09-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0025_sessionplan_name_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplanpathbinding',
            name='role',
            field=models.CharField(choices=[('frames', 'frames'), ('sums', 'sums'), ('mdocs', 'mdocs'), ('parents', 'parents'), ('atlas', 'atlas'), ('tilt_series', 'tilt_series'), ('gain', 'gain')], max_length=16),
        ),
    ]
