# Generated by Django 5.2.16 on 2026-09-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0026_thumb_url_proc_software'),
        ('tem', '0026_binding_role_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='gain',
            field=models.ForeignKey(blank=True, help_text='path pattern to the gain reference files this camera writes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gain_type', to='stores.pathtype'),
        ),
    ]
