# Generated by Django 5.2.16 on 2026-09-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0027_camera_gain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text='Names a plan profile. Blank on snapshots.', max_length=40)),
                ('super_resolution', models.BooleanField(default=False, help_text='Camera wrote super-resolution frames: frame pixel size is half the calibrated one.')),
            ],
            options={
                'verbose_name_plural': 'acquisition settings',
            },
        ),
        migrations.AddField(
            model_name='msisession',
            name='acquisition',
            field=models.OneToOneField(blank=True, help_text="Snapshot of the plan's acquisition defaults, with the operator's overrides", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='tem.acquisitionsettings'),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='acquisition_defaults',
            field=models.ForeignKey(blank=True, help_text='Profile copied into each new session; the operator may override at create time.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='tem.acquisitionsettings'),
        ),
    ]
