# Generated by Django 5.2.16 on 2026-09-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tem', '0028_acquisition_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='camera',
            name='model',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='microscope',
            name='energy_filter',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='microscope',
            name='image_correctors',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["Cs corrector", "Cc corrector"]'),
        ),
        migrations.AddField(
            model_name='microscope',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='microscope',
            name='model',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='microscope',
            name='phase_plate',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
