# Generated by Django 5.2.16 on 2026-09-24 18:33

from django.db import migrations, models


def null_out_existing_usage(apps, schema_editor):
    """Existing rows predate these flags: usage is unknown, not "not used".

    AddField set them to False; reset to NULL so a re-run won't clear valid metadata.
    """
    AcquisitionSettings = apps.get_model("tem", "AcquisitionSettings")
    AcquisitionSettings.objects.update(phase_plate_used=None, energy_filter_used=None)


class Migration(migrations.Migration):

    dependencies = [
        ("tem", "0029_instrument_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="acquisitionsettings",
            name="energy_filter_used",
            field=models.BooleanField(
                default=False,
                null=True,
                help_text="Energy filter was operated (installed does not imply used); null = unknown.",
            ),
        ),
        migrations.AddField(
            model_name="acquisitionsettings",
            name="phase_plate_used",
            field=models.BooleanField(
                default=False,
                null=True,
                help_text="Phase plate was operated (installed does not imply used); null = unknown.",
            ),
        ),
        migrations.RunPython(null_out_existing_usage, migrations.RunPython.noop),
    ]
