name: Django CI/CD for yb-grid-api

on:
  push:
    branches: ["yb-grid-api"]
  pull_request:
    branches: ["yb-grid-api"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    # - name: Install Dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    - name: Deploy to Production via SSH with Password
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VM_HOST }}  # The IP address or hostname of your VM
        username: ${{ secrets.VM_USER }}  # Your SSH username
        password: ${{ secrets.VM_PASSWORD }}  # Password for your SSH user
        port: 22  # Default SSH port, adjust if different
        script: |
          cd /home/yongbaek.cho/czii-umbrella-django/umbrella
          ./deploy.sh