name: Jest Unit Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    if: false
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: "./frontend/.nvmrc"
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Run Jest tests
        run: |
          cd frontend
          yarn test
      - name: Upload Jest test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: jest-test-results
          path: frontend/jest-test-results/
          retention-days: 30
