name: Deployment Testing
on:
  push:
    branches:
      - autodeploytesting
jobs:
  build:
    timeout-minutes: 5
    #if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_PRIVATE_KEY }}

      - name: SSH test
        run: |
          cd ${{ github.workspace }}
          ls -alh
          ssh-keyscan -t ed25519 ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "ls -alh"